apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: middleware-tiime-finops
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/dromadaire54/test-poc-applicationset.git
        revision: master
        directories:
        - path: k8s/middlewares/finops/*
  template:
    metadata:
      name: '{{ `{{.path.basename}}` }}'
    spec:
      project: 'default'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
      sources:
        - path: '{{ `{{.path.path}}` }}'
          repoURL: 'https://github.com/dromadaire54/test-poc-applicationset.git'
          helm:
            valueFiles:
              - "values-prod.yaml"
            ignoreMissingValueFiles: true
      destination:
        namespace: 'argocd'
        server: 'https://kubernetes.default.svc'
