{{- if and (hasKey .Values "pgbouncer") .Values.pgbouncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "database.pgbouncer.name" . }}-deployment
  labels: {{- include "database.pgbouncer.labels" $ | nindent 4}}
spec:
  replicas: {{ $.Values.pgbouncer.replicas  | default 2 }}
  selector:
    matchLabels:
      {{- include "database.pgbouncer.selectorLabels" $ | nindent 8}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "database.pgbouncer.labels" $ | nindent 12}}
    spec:
      initContainers:
      - name: install
        image: akubrinsky/envsubst
        command:
        - "sh"
        - "-c"
        - "envsubst < /base-conf/pgbouncer.ini > /conf-dir/pgbouncer.ini; envsubst < /base-conf/userlist.txt > /conf-dir/userlist.txt;"
        env: 
          {{ include "pgbouncer_config" . | indent 10 }}
        volumeMounts:
        - name: confdir
          mountPath: "/conf-dir"
        - name: pgbouncer
          mountPath: /base-conf
      containers:
      - image: "bitnami/pgbouncer:1.19.0"
        name: pgbouncer
        livenessProbe:
          tcpSocket:
              port: 6432
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
              port: 6432
          initialDelaySeconds: 20
          failureThreshold: 6
          periodSeconds: 10
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - '-c'
                - >
                  wait-for-port 6432; sleep 5;
          preStop:
            exec:
              command:
                - sh
                - '-c'
                - >
                  "kill -s INT 1 && sleep 120"
        volumeMounts:
          - name: confdir
            mountPath: /bitnami/pgbouncer/conf
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 64Mi
            cpu: 50m
        env:
          {{ include "pgbouncer_config" . | indent 10 }}
      - image: "prometheuscommunity/pgbouncer-exporter:v0.7.0"
        name: pgbouncer-exporter
        args:
          - --pgBouncer.connectionString=postgres://$(POSTGRESQL_USERNAME):$(POSTGRESQL_PASSWORD)@127.0.0.1:6432/pgbouncer?sslmode=disable
        env: 
          {{ include "pgbouncer_config" . | indent 10 }}
        ports:
          - name: metrics
            containerPort: 9127
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 64Mi
            cpu: 50m
      volumes:
      - name: confdir
        emptyDir: {}
      - name: pgbouncer
        configMap:
          name: {{ include "database.pgbouncer.name" . }}-configmap
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  revisionHistoryLimit: 2
{{ end }}
