argocd-template-helm:
  argoApps:

    backup:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "values-preprod.yaml"

    rbac:
      enabled: true

    teleport-agent:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "values-preprod.yaml"
              - "secrets://values-secret-preprod.yaml"

    teleport-role:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-preprod.yaml"

    tiime-network-policies:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "values/preprod/values-middlewares.yaml"
              - "values/preprod/values-chronos-apps.yaml"
              - "values/preprod/values-data-apps.yaml"
              - "values/preprod/values-qa-apps.yaml"
              - "values/preprod/values-hub-apps.yaml"

    old-tiime-satis:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-template.yaml"
              - "values-config.yaml"
              - "secrets://values-secret-preprod.yaml"