argocd-template-helm:
  argoApps:
    karpenter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-preprod.yaml"

    karpenter-crd:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"

    keda:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"

    kube-downscaler:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
