argocd-template-helm:
  argoApps:
    aws-ack-rds:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-preprod.yaml"

    aws-ack-s3:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-preprod.yaml"

    aws-load-balancer-controller:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "values-preprod.yaml"

    aws-mountpoint-csi-driver:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-preprod.yaml"

    aws-emr-flink-operator:
      enabled: true
      spec:
        source:
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "values-preprod.yaml"
