argocd-template-helm:
  argoApps:
    # The headmaster umbrella chart
    tiime-headmaster:
      appsNameOverride: tiime-headmaster
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-headmaster.yaml"
              - "values/cluster-prod/values-headmaster.yaml"

    # # Apps umbrella charts
    tiime-chronos-umbrella:
      appsNameOverride: tiime-chronos-umbrella
      enabled: true
      finalizer: false
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/argocd-apps"
          targetRevision: "main"
          helm:
            valueFiles:
              - "values/cluster-prod/apps/values-chronos-apps.yaml"
        destination:
          namespace: argocd
        ignoreDifferences:
        - group: "*"
          kind: "Application"
          jqPathExpressions:
          - .spec.source.helm.parameters
        syncPolicy:
          automatedEnableDefaultConfig: false

    tiime-data-umbrella:
      appsNameOverride: tiime-data-umbrella
      enabled: true
      finalizer: false
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/argocd-apps"
          targetRevision: "main"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "values/cluster-prod/apps/values-data-science-apps.yaml"
              - "values/cluster-prod/apps/values-data-analytics-apps.yaml"
              - "values/cluster-prod/apps/values-data-engineering-apps.yaml"
        destination:
          namespace: argocd
        ignoreDifferences:
        - group: "*"
          kind: "Application"
          jqPathExpressions:
          - .spec.source.helm.parameters
          - .spec.source.targetRevision
        syncPolicy:
          automatedEnableDefaultConfig: false

    tiime-hub-umbrella:
      appsNameOverride: tiime-hub-umbrella
      enabled: true
      finalizer: false
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/argocd-apps"
          targetRevision: "main"
          helm:
            valueFiles:
              - "values/cluster-prod/apps/values-hub-apps.yaml"
        destination:
          namespace: argocd
        ignoreDifferences:
        - kind: "Application"
          group: "*"
          jqPathExpressions:
          - ".spec.source.helm.parameters"
        syncPolicy:
          automatedEnableDefaultConfig: false

    tiime-llm-umbrella:
      appsNameOverride: tiime-llm-umbrella
      enabled: true
      finalizer: false
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/argocd-apps"
          targetRevision: "main"
          helm:
            valueFiles:
              - "values/cluster-prod/apps/values-llm-apps.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false
        destination:
          namespace: argocd
        ignoreDifferences:
        - kind: "Application"
          group: "*"
          jqPathExpressions:
          - ".spec.source.helm.parameters"


    # Middlewares Umbrella charts
    middlewares-tiime-aws:
      appsNameOverride: middlewares-tiime-aws
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-aws.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-aws.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-finops:
      appsNameOverride: middlewares-tiime-finops
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-finops.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-finops.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-miscellaneous:
      appsNameOverride: middlewares-tiime-miscellaneous
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-miscellaneous.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-miscellaneous.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-networking:
      appsNameOverride: middlewares-tiime-networking
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-networking.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-networking.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-observability:
      appsNameOverride: middlewares-tiime-observability
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-observability.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-observability.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-qa:
      appsNameOverride: middlewares-tiime-qa
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-qa.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-qa.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-scaling:
      appsNameOverride: middlewares-tiime-scaling
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-scaling.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-scaling.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-security:
      appsNameOverride: middlewares-tiime-security
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-security.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-security.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    middlewares-tiime-web:
      appsNameOverride: middlewares-tiime-web
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-default-settings.yaml"
              - "values-middlewares-web.yaml"
              - "values/cluster-prod/middlewares/values-middlewares-web.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    # # Middlewares in the headmaster umbrella chart
    argocd:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "secrets://values-secret-prod.yaml"
              - "values.yaml"
              - "values-rbac-prod.yaml"
              - "values-prod.yaml"

    argocd-project:
      appsNameOverride: argocd-projects-prod
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-projects.yaml"
              - "values-default-settings.yaml"
              - "values/cluster-prod/values-projects.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    argo-rollout:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "values-prod.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    tiime-system:
      enabled: true
      spec:
        syncPolicy:
          automatedEnableDefaultConfig: false
