teleport-kube-agent:
    joinParams:
        tokenName: ENC[AES256_GCM,data:xhNEGqKCL8n+v14xJ8NA6Auowbf722UhmFQemNxkx2k=,iv:LtsJUuZqWWm4HMpsEFfHY2f6bqXnxhGZEDMEdZoKAsU=,tag:2ahzYAhY/2X6thUU8b2kuA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-12-02T09:21:19Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgFwA82I/Vw/GkmvMAwtso7OAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlvfo98FhWvSF0Mf3AgEQgDt9PieENcIIUrOcbuSGnwK+tt9HiWa0NL3reT3ayy9czfzo5OaLCtiJPrbwb9LTErZc3QkvbIuG/hbqkA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-02T09:21:20Z"
    mac: ENC[AES256_GCM,data:YLq4rXccO117JB84TFQ20H3tf7cLe78wU4qrYuOBV8hkFT2NiKlQtXqID/VRKzm75FoLas9cq9M8UyL0cNkT+awwtbUBwSEG1Xd5C0bUHGR1MOSVuEt+yPV6kNHauVR10nUBba2kb4jHknzKgKA4Zg6OGcdPL5lejMmz844xdCs=,iv:Gye969NUK24VbQyUoQIB00/K3Moef7gGX8OB3yZYDXo=,tag:/meq36ARWAiq5FBC3hyiUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
