teleport-kube-agent:
    joinParams:
        tokenName: ENC[AES256_GCM,data:fX2xl5HfnZKup/v/vKoPMlW+UiKtfJQRlH2PXZDsOi4=,iv:ZuW4I5u/3CJ+zZnBtvynugrSLrIbNRf7Z+Sals+TRSk=,tag:bOgQVJ8gigGZt4KNNWkozA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-11-27T14:25:44Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgEiLsL/gyrCMMpvMJLEcfH+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrAWpoMmcvdsGeTmKAgEQgDt+VNibFrf+kdaee3ZjQB4R3bNzxmZo89LuX7I5M7wu/tZGJ2VRs7j/DNq5pkETFxw+VXn04vylQ+TbAA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-27T14:25:44Z"
    mac: ENC[AES256_GCM,data:2Z3+tUJhAu7gQ2NHLQ3QGL75x+K3bbxCFrW6uHMOJHLB9QUdx1vHGLMYUbLf/BK/gNPL2cDdEwi5f42WlHkwr1WrhdS2sq6Q9RTY5Bz/1oWJeuMf85CSVPISngJX/HsTjcHcvnnRkdVSgUPkrVHtcnMsbTL/rbOycQjuMfIW+fA=,iv:y14LPOJqnBcO0f9IAdB9coFf8J07GgidLr8cez6gkDI=,tag:/qO+vJc17wVDiZTuUchCJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
