{{- if and (hasKey .Values "postgres_exporter") .Values.postgres_exporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{(index .Values "prometheus-postgres-exporter" ).config.datasourceSecret.name }}
  labels: {{- include "database.postgres_exporter.labels" $ | nindent 4}}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  {{(index .Values "prometheus-postgres-exporter" ).config.datasourceSecret.key }}: "postgres://{{ $.Values.database.user }}:{{ $.Values.database.password }}@{{ $.Values.database.host }}:{{ $.Values.database.port }}/{{ $.Values.database.name }}"
{{- end }}