argocd-template-helm:  

  argoApps: 
    argocd-project:
      appsNameOverride: argocd-project-preprod
      enabled: false
      spec:
        source:
          helm:
            valueFiles:
              - "values-projects.yaml"
              - "values-default-settings.yaml"
              - "values/cluster-preprod/values-projects.yaml"

  argoProjects:
    chronosProject:
      enabled: true

    dataProject:
      enabled: true

    dataScienceProject:
      enabled: true

    dataEngineeringProject:
      enabled: true

    dataAnalyticsProject:
      enabled: true

    hubProject:
      enabled: true
      
    opsProject:
      enabled: true
      spec:
        destinations:
          - namespace: "*"
            server: https://kubernetes.default.svc
          - namespace: chronos-development
            server: https://kubernetes.default.svc
    qaProject:
      enabled: true
      
    webProject:
      enabled: true

    llmProject:
      enabled: true
