k8s-monitoring:
    destinations:
        - name: ENC[AES256_GCM,data:X6VJsZ9q9/tLJ7CLCmk=,iv:op0eEHpU1+GlfudcANuIJSIZT08zJpxpO7lp+ILrnJo=,tag:Xqj64sJZi70fy7HDEOkYeg==,type:str]
          type: ENC[AES256_GCM,data:QvjVWhko3SmMtQ==,iv:uRK2ANp8O9o88arVPjQmdQ+8MtL0EPa1MF/33Yyt2Pw=,tag:wzXMChizcpHQrPaSs5DrSw==,type:str]
          url: ENC[AES256_GCM,data:wdBPDq2XhdfaWRKD9zV01IZdxXwm9H2KfwmJzZhQC8oncCCPY3nb1/+VbXjoYbVRrgeqgB8iQR3+wXaCF758+Evdq1mLhT4NT97l,iv:7zRHwOQVOeI05/wC0Sd2yVGUY8hMSWvkFPkNoFPoS8Q=,tag:aS+7Pr2Ra5y8u9UOOGl8sA==,type:str]
          auth:
            type: ENC[AES256_GCM,data:+RNXULQ=,iv:QxEg8vBe96mcIU7NBylTVDvWT82AIZEO/+voo3zb584=,tag:e1/Q45kMV/R6+W97afGnQg==,type:str]
            username: ENC[AES256_GCM,data:++AafyPKwA==,iv:g9edwX/Esakzp0bxInUs9KX1M8wyQTotqNDYNcaXZRQ=,tag:/siCx3MoOgpy9e9JTQ9L3Q==,type:str]
            password: ENC[AES256_GCM,data:KK0dr9+gjevLw0Y4IAtedpMqviHX3OvI0nhxiyhiDC7APzJFJCJjXXOHzsb7Fz8P8oSHrXrW9Z+zr/fG/r7OJ0tAFIhHJWOTmf4kxKr8abyLJJL1xKTSbYgWsb35UJdIFIkm/e8rfj9WIycpnGZZkxq3yay69ZiQNJYPPSqNsSYlTEDkkVBVBk2RyBQJGd0Z5vNYA7LxHHU8zVzFO9KezlxQGlpc5K/jKe6SujpRMzReJDyynykbE6P8/Nu6A8OR,iv:RBuMVc3VN/j4f2sTs/ntV01p+L0/DjLALD1zwsS0XLY=,tag:/Ju8slNtd7Qkv2TNMT5/iw==,type:str]
        - name: ENC[AES256_GCM,data:CRRfylY+0aO4hAE=,iv:DIa9h2rbbHBMmdUSDvqh/zJy5mV5pcprh0OlUiw+7Dw=,tag:OMgvlTE6Jd8jL1cH7lIQUw==,type:str]
          type: ENC[AES256_GCM,data:GkwMNA==,iv:W1E3YP/CwM2lH5fl15mROrZuyZr2TWxEIFO53AbdQ3Y=,tag:eADi4dTjiyV2fCmUsn+P3w==,type:str]
          url: ENC[AES256_GCM,data:z6i1hnj6mLYPmkkTGm/9bV7HYq53JVeJexS43xPwytq/HcFCYMaxA9O3SSpPX0M3vz9wwlTRGbf+EyTqKutDNKWmX29lGqB7y1zyJYV4,iv:wTPDWWz9nrpzJXsMcavHQPd42Egi8AzNmSdEdUm/lbU=,tag:4Bgcpo8h2s94oQCrBPBmhA==,type:str]
          auth:
            type: ENC[AES256_GCM,data:6eqA4S8=,iv:dQzYJ7CgFmLtlrBCoDs0MY/s+9c0X/RVxQJ+OuDs0Pk=,tag:Q2EQ3xa7QxA8izobI5N5lg==,type:str]
            username: ENC[AES256_GCM,data:6fkGKsQE,iv:EUZU8OApA/Bzt8sffnUZj3XLz3xf5u1A+uv+vs3jlpg=,tag:Z6kBJLQDPzP2IfjcE3ldQw==,type:str]
            password: ENC[AES256_GCM,data:u5f0xYrrxPZdvfXUwNingtNdtjVwVjn8J2yC5jjOcrfWg+Dde5bqiGiz4b/IvwPoSAlg99KClwcppbWf5pZkVLnEdjO+CBTsbPVLsKeCl1JXWwh9GffvGCklg+SqkRX8apNrq5YK59nqej7LZoh4kTrT3KzJE7HNoNefhWkBrxdKuObUtGmu3EU9sAIV5oPT6g6qHP20ywIQwS1vtB1Gk3DJMSkHfiAa/Jghu995xol/zOP+Ul/VsCzS3cNytz4L,iv:rbt2sDwrHO3hjWkfOYrbTOGdXhrDGXZOk2xObP6Lm5M=,tag:OhJ74tZiEjdqaUv0Li1oiA==,type:str]
        - name: ENC[AES256_GCM,data:9wZhdPro6z6gK3Z9kA==,iv:7uSp7VMZA9cGxW6xM4dNbDG3zhTFX+MTPp4CqQ+pmrc=,tag:gitngbO7aPYldEfyIbE1Uw==,type:str]
          type: ENC[AES256_GCM,data:rIJb2Q==,iv:uPU+RMcCchRUlXpOEobyX2rrOKEq+bjcn3zZW5Ot3oE=,tag:u4GAHfqMxFwXjmF0eCBf1Q==,type:str]
          metrics:
            enabled: ENC[AES256_GCM,data:sRx2TGg=,iv:EeZoeIjsmt7HwNIPv4XNPTAmt1kGFjIfNyIZMnBmiK4=,tag:NPZy9NNOhhFPSbU6j8IXmw==,type:bool]
          logs:
            enabled: ENC[AES256_GCM,data:AOUGdD4=,iv:Ac8/TKdRQCo/uDTlnCDdZIeAafR/c22e7rhJexpxv+o=,tag:f3fz/3FKkZ9TU8Ww4m4RLQ==,type:bool]
          traces:
            enabled: ENC[AES256_GCM,data:IwwYtw==,iv:cQYYXBEoOihI3GttLjkfFvtPx4ghhIzVbTMdaWc22dU=,tag:2erSq8n+bWaT1RQ6LMn7JQ==,type:bool]
          url: ENC[AES256_GCM,data:7aTQwZXdLYfiIJ7MWyCJIfowGIMjj8Osc2hVKSrEGO2BwNS9vvLToDkGYg8tmM1Bm9F1PJLk212zePqhKQ6Mi3Q=,iv:BPo17tQqw3Z+F8Va37syU+NXPzZ71BkhHnVAgxBdUIM=,tag:EmnmuLRJSVDcs8zk6MJM7w==,type:str]
          auth:
            type: ENC[AES256_GCM,data:vj/JZ1c=,iv:kJfEtEdv3QYeyqgS6YmJk1cuyDO+lH4DepSwlru2YnM=,tag:zatO75pE5MGZM74DYfCghg==,type:str]
            username: ENC[AES256_GCM,data:5fpmw3tc,iv:FUwf56GPe72qc50gW5nBkgn5XrBxG7y2tn102EIYwR4=,tag:h7oWiRp8wV3vi9SIZLFCxw==,type:str]
            password: ENC[AES256_GCM,data:yBQdRfJcTBNR/WIlhTEdQQfgQZdUNDYgqqLP2hj1ZdUdCtWCk6llogciqBJ818Ncxb9RWEqERF0sAFe8reeSGi6UQhawlkEVR3gc2YkmNilSBu/+pSvQWDiafCF5KHB0qosIuq5wsibNU1vOLqEomM30iGgVUpLAs+5PVNKWZt9cbQKd9IGVzxugFgTT6jFWGqCJwHghyzKLLfYUdHmlykigIKqiXRZxe2TVsmpUWH+ZLcqVzYSJbh7CybFCfcmx,iv:65ET0T2/I7jANHGuFmUiUftWFBPo482pxKQTldxAu4A=,tag:hmU2L2F2/3nkO80v6ltJaA==,type:str]
alerting:
    password: ENC[AES256_GCM,data:cX8n8hpZYXqgAMKXy6yMG4LsMu6xd/M1mYdi+1+o82xBf7xK5T6F33OC9VrtNslh2nf3yo4DE2VM5Hce6ZBV8EooadqeWFL3//7Zeyfvs+SbFV0NM6F4i08GH9RYtisyDbcrnAkukflGrDNscaRD0s+O426e8XkcMjmWeXeQhQ782zvb3bUpQPM/TY3am38nKJbtFg==,iv:CkoFht/iY7EPgthpw+JrHgeZ5dwJXw69fYEGZWulK/M=,tag:FA9wi6WEzkktxDMDz0SXrg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-12-02T09:20:18Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgF7XjQYqtKlTdOuFX/NdZr4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMEeZsmlc0gsqU0fvAgEQgDtXp4PRvAJlTokB/es5JSkUIRnYNM4cd+PSFKSuXBctUto5bqs+AYMngY4Io0fXwP1+APtdUkU/n2NPCg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-22T07:45:20Z"
    mac: ENC[AES256_GCM,data:CQUYgAsAkSH/4VyHq+xHi+iw/u5Q3VlmT13VEAxia9CUEvRFdFzc95xK6vkfxb8mkyb2qTav7+as4qkuiHlL6BDAYJLoru4neUHRiiqtH7ExHCZuU8wqem1SiEvaW2/LO/0+Hg630b57RoPNRZT/y9ABZGGrS2VaZvwCk9AiNlo=,iv:CkSqfIeyLCn0v7PKnUnmvlbmZMVMklYuF+5h6ibW8DU=,tag:agsd1qsIQmjArnzunvaH+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
