k8s-monitoring:
    destinations:
        - name: ENC[AES256_GCM,data:QRr/TDtKFXcWDpDkfB8=,iv:pHsRczwW6KYieKVcQnGP3CkPsNCUnaGW6fL938mCzeM=,tag:j+OU+aFEYJrwVHtJhOdvLA==,type:str]
          type: ENC[AES256_GCM,data:nKC673/hbQg/7w==,iv:JPjfyLYvkwaNC8l+2iTTFqIDPGqUlw8rdtuGbMnbG68=,tag:meN6k3M61eJyz/rc8GEdaA==,type:str]
          url: ENC[AES256_GCM,data:tuaDqO6/yogoZkKvW6LqZf1CztkzmNINn7R8ttw59OxOvEo25wJLW13lTJz3bbH0skuZUUsOL1MUt+Ol+ZPhVUmtz45XReInl5a8,iv:JbYjsgSjyZutDqz2NVmDiHOGBmOiRgMiFyIQViYHaXo=,tag:K10gk2fpGzn/w6B9FYJ1Ag==,type:str]
          auth:
            type: ENC[AES256_GCM,data:QwZ0MKY=,iv:tWC3jLxxngI1sIGzwjkZnE764IPAFDQgAqfe8yOQ7tU=,tag:9JtLvQ1GUIU8Hw1MbfGIEA==,type:str]
            username: ENC[AES256_GCM,data:SNhHiuCnOg==,iv:aaTDt6kb+jWKIr1FyM1JiXyj1A4C1X6EJ3z5seEdchU=,tag:Eqf7ElwXMq4Olcv9iTCpoQ==,type:str]
            password: ENC[AES256_GCM,data:Zn9Nxwckv47+tjGdZQztkPtWzeAiUvamL6W47DYI3s/NDdwVrYTW+DQ/Eo2UZXx4fnauvJTko7YO/a3PbWDhTFbcm0MEf7RUF6HQO3vh7Fg1/c21FfeFuA8+ahtA6JpqKC1ugK1eumiBOzZDE9Zzw8XAecBuZb2W/Dv7xDFUqkFh9Zfsrh11eKrM+hD3/0IGRq7ZBVAs2Y7/a/O3bjaNN2Km/DFoN7nMI9G1DgHNJkCVjPJyaJi3k7fGCqZGJ/K2,iv:2GeGs8pk5l+o6JVUj19SkOFdFtEdkrM/WBHbFnOVAoc=,tag:Fw3aDpfCSbKVX4T8ZbKj2Q==,type:str]
        - name: ENC[AES256_GCM,data:6UoXRHQxtx8xAW8=,iv:cLI91Wd0lVKgSi2zjY0FTZJzK/4Gfd8Henls2bJqH6U=,tag:PDQesRtv8nIsWCUo0ce3BQ==,type:str]
          type: ENC[AES256_GCM,data:P+9BRQ==,iv:epFXpevunQsSWh9ylVodl/DdZ/uvxHpRkkF1KdgNElo=,tag:7TbYwW8/hgXzObfmaOs9Vw==,type:str]
          url: ENC[AES256_GCM,data:pP21l0fVAWprVO8P5MWRpMmWjAZJHnY0xunV1Kz47Y5Tj89olyJ9GhjC8H5XjrnJgkU5U6CA5xP6zxK3kTf27BoKMh9czA6T+RI+S5iv,iv:YabiL9zuxX/401Bx1BYyDX8QpW2lqZJAqYZam4kavcU=,tag:215SLTawwwotk9W9Xsmblw==,type:str]
          auth:
            type: ENC[AES256_GCM,data:Ll83Wkg=,iv:0Aa1MiZAg95eJPCsyR4DcTFPUFNsWfW/fufO66XQfaQ=,tag:flAaRYs6mViYNIQIs08paA==,type:str]
            username: ENC[AES256_GCM,data:sdiE6wWp,iv:dJ1USUWCm93o+lKcECaYy9OLdCTOmcUBgue9w9AzxyI=,tag:dF3Xeh6aAicxvy3T+woO+g==,type:str]
            password: ENC[AES256_GCM,data:9RN1ZfSzmwKjrHDuecnLlrKY/66mg2KVIl6hua/bJ8WE0dF7UsQs4Rf9dxoyZ+Ck2fvQXfl/yqkkqAJVRK+cYkm6yYa2rCS9UWK2p4TaEDJwJ7QglFl1sye3uodp4Y1M7KtKFogBtYy8ps8U3X/wvaaoldUEgeEtOcM2ePe8yFxHFQvJ17mH+MUlJvAYSJIBRmIBf72/PVsyO91fix6im9KPMT/vwL6YHgqD9NDFRva7Id5EadwO1ZxXr82Fworp,iv:DAN2OOf9D2sgqByU2p7J1XKkpNvKm+HgQnAyzMQeGF4=,tag:1cgtzr4yb9CvwJRuBalpTA==,type:str]
        - name: ENC[AES256_GCM,data:D4ppaYf8MhYH3xbryA==,iv:cV6AN0gNwBbH3kj+IxRtK/TMAJyE9p/dBpIXnWfn8xY=,tag:NAobNDrsN3CkgfBL0v5SGQ==,type:str]
          type: ENC[AES256_GCM,data:YGysiA==,iv:5VnCapAitixutMw6QD1z561dG94zJ8Bvq8E/nAuSU60=,tag:l2VeaacrIDK8f3/Emd9Spw==,type:str]
          metrics:
            enabled: ENC[AES256_GCM,data:O9CMoA8=,iv:6WLZkF8pvqJoJHOvxnVD2xn6d7PlvH+OTITNum9jppw=,tag:ZZhpi+PLoQkrXcCDld8vYA==,type:bool]
          logs:
            enabled: ENC[AES256_GCM,data:x6YVO0E=,iv:54iPbngTbC4DvAsYBh9JCwXuMvTSUf4ddo4+w/6/3fw=,tag:o0E+Sp/UW9whByDmaDBs5w==,type:bool]
          traces:
            enabled: ENC[AES256_GCM,data:AQyo4w==,iv:zEBLSKfH//M1DthcvHZcbxEcW54Qg8iKxT0NV+X+asM=,tag:ltEf4UtnqT80Qieepx72Nw==,type:bool]
          url: ENC[AES256_GCM,data:bKwkimsr/1FlymyzT9ChbdRMpyyBa1SDn+un+JYBzZ8zGpC19YjRNmoDPpVMa+yYWO7XalNMbJmg/BsH5r33208=,iv:0/kH6DZTQ/+fXaRXB4B2Ug9DqixtKex4o1V++davn04=,tag:DU9qpxQnvTsvt9vAwxj3YQ==,type:str]
          auth:
            type: ENC[AES256_GCM,data:GbkeGkA=,iv:caK4HGza0j9s79ddTkJ6EVl8AUEHLLpXoh52rzVDs10=,tag:aNDPBq4u9/sE78qcJ1uDDg==,type:str]
            username: ENC[AES256_GCM,data:YVaq9AaX,iv:5P0hb+dFmYGIu7dz6fQkI1Q+lplqlvheuoWYBsQ1XqM=,tag:vOzE4RqaxpmrWD2V61Su6w==,type:str]
            password: ENC[AES256_GCM,data:VIlgsQTzrHgnbllxFnwX2f57czLWz4OGy45/+1xbucx2FNCeuRHyT3zu9xhNR8hRA2lnq62ST39X2l+H2p0ZoUkHra6DWYuMiZc3eISeS45EIgp/FGD5/05OH+S+Bt5wcOAxA/hNWS07m7Uj3XTcHaS16vLs3SmqzFpfJaZmI6Hj/S+ZVMkhbz3HQMC8mYRvuJtq4aJ7pIqXe4AvKneal0Hx7z94RFsabNkoq0H+pqXZR1cd5J2lG9ZovCj1MIjy,iv:bM6KMoC4T8Uxtk8SjxIvuSaLSV3L3iQi+Bp3Y14ijt0=,tag:komw43+6ZgF9MHhjCHn+vA==,type:str]
alerting:
    password: ENC[AES256_GCM,data:fH2Fp6PltRH2hzxTqOjFuJjrVDcBZAjBIDIAhp0wliBBg+yOMkxlj0LNjIDgHDL8x7sAJ+hsfJCto4u0wpjQno6lzwSL/loUOtaantRIkd8h4vrHzCjk7avvEDxC9RVKjdUcySXn/vgoU6OiGtPKwmB/9ULgu1KIcP++z2EGpTwk0lVJ0wYwsXhnZky4csTyXK/PfA==,iv:3T22+umm3BfAs5Ma9JSbu+c/JjRt1fNk+oWa9gb1o8U=,tag:Gls6qp9B753ycW6W9eiFVQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2025-07-21T15:30:54Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgF5rvUQ2UNzVncfaecjf3tnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM89HwN2RW/JnmHxSLAgEQgDuo8yGX2ToFgsp7XKNnjdxhLZ5nAfxEO4mjsZMVRdROHKQn+V9c10t5JAwNCVpbDDv1JEwP/aZPQayjYg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-21T15:30:54Z"
    mac: ENC[AES256_GCM,data:n/hSxkYZlJacteDUhyZctAdGcSl6C7Kv6d+VPBctFz7jiCdFgTrwOwjHVuVaURbaJ6M4KTEKf0/ECiWlXtRaZcy+PGjAfiJF91mJXALEHKAMXwUx8P+sc52Bw2MWzDg0E0AgcbYc7PZJH6s+yCEZiU1T3dwEBY6Cq2ZgTA17QMY=,iv:q2mvSNT1E6FkpqxC6u9dlomotWsEEjeIWSUsjN+Xq3A=,tag:+miOEgRqtGgorC+LiDiEJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
