{{- if not ($.Values.global.maintenance.enabled) -}}
{{- if hasKey .Values "workers"}}
{{- range $workerName, $worker := .Values.workers }}
{{- if hasKey $worker "autoscaling" }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $workerName }}
  labels:
    {{- include "worker.labels" $ | nindent 4 }}
spec:
  pollingInterval: {{ $worker.autoscaling.pollingInterval | default 30 }}
  cooldownPeriod: {{ $worker.autoscaling.cooldownPeriod | default 60 }}
  maxReplicaCount: {{ $worker.autoscaling.maxReplicaCount | default 50 }}
  minReplicaCount: {{ $worker.autoscaling.minReplicaCount | default 0 }}
  scaleTargetRef:
    name: {{ $workerName }}
  triggers:
  {{- if ($worker.autoscaling.cron).enabled }}
  # https://keda.sh/docs/2.11/scalers/cron/#scale-to-0-during-off-hours
  - type: cron
    metadata:
      timezone: {{ $worker.autoscaling.cron.timezone | default "Etc/UTC" }}
      start:  {{ $worker.autoscaling.cron.start | default "0 20 * * *" }}
      end: {{ $worker.autoscaling.cron.end | default "0 24 * * *" }}
      desiredReplicas: {{ $worker.autoscaling.cron.desiredReplicas | default 0 | quote}}
  {{- else if ($worker.autoscaling.postgresql).enabled }}
  - type: postgresql
    metadata:
      connectionFromEnv: DATABASE_URL
      query: "SELECT count(*) FROM messenger_messages WHERE queue_name = '{{ $worker.queueName }}';"
      targetQueryValue: "{{ $worker.autoscaling.queueValue }}"
      activationTargetQueryValue: "{{ $worker.autoscaling.queueActivationValue }}"
  {{- else }}
  - type: rabbitmq
    metadata:
      protocol: http
      queueName: {{ $worker.queueName }}
      mode: QueueLength
      value: "{{ $worker.autoscaling.queueValue }}"
      activationValue: "{{ $worker.autoscaling.queueActivationValue }}"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}