apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pg-badger-slack-channels
  namespace: {{ .Release.Namespace }}
data:
{{- range $cronjob := .Values.cronjobs -}}
{{- if hasKey $cronjob "slackChannel" -}}
{{ $cronjob.name | nindent 4 }}: {{ $cronjob.slackChannel | b64enc }}
{{- else -}}
{{ $cronjob.name | nindent 4 }}: {{ $.Values.default.slackChannel | b64enc }}
{{- end -}}

{{- end -}}
