apiVersion: v2
name: kube-downscaler
description: A Helm chart for deploying kube-downscaler

type: application
version: 0.2.5
appVersion: "24.8.0"

dependencies:
  - name: py-kube-downscaler
    repository: "https://caas-team.github.io/helm-charts/"
    version: 0.3.5
    