apiVersion: v2
name: pgbadger-report
description: Helm chart deploying a cronjob running pgbadger and sending its report to Slack
type: application
version: 1.0.0

dependencies:
  - name: security-template-helm
    repository: "oci://851725266353.dkr.ecr.eu-central-1.amazonaws.com"
    version: 1.0.2
