default:
    slackChannel: ENC[AES256_GCM,data:+GIQpCHdXm2Evy8=,iv:/Ug9ypz/I+rMBesAv3Rs5vWdHiMLx+WFL3LU+S3wlxk=,tag:7PQIXiDNJG4q4+OIVBxd7g==,type:str]
    slackToken: ENC[AES256_GCM,data:fw8TQ726e8TnFQ6j1tRr1k3F+muKqZsByFvW9nQwOUW/TU91HnSFsg3NPu4y21XbpbJJzHUU,iv:kKes+3mx6gsTEQF3wICVLw+c8Z8JnaEWUcD6OFx+S+8=,tag:CdBH0tDXNGWcyz7i6m/bkA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-12-02T09:20:54Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgEppUerwNwISH0HBt8rwv7XAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcuuwCZ0LGkJAyY1lAgEQgDt2dv7h8jQe1BV8fz9k9Ln5YM9dm9j9NUzvi6Q93FR+d/V5W50ee29ORWULN3lC2FQqugwmGYlpCc94qg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-02T09:20:54Z"
    mac: ENC[AES256_GCM,data:Q4zWW+qpNtaghDSgujE6WBPKRE138z+RfbxYfJxIhN8hrZhjeYs7FepFQN/FpKbIZAYEPLOSaTajxPYANt0OuBdxRJfR4VHcEj9cJKm9zmzo520exNcA4GSed9Gsv9H5AAD0Mj6N+0HCsKQ4s0IHgcGzBhjUAg0lkNMMPPk/Yic=,iv:6qwxmoGyvr7Fg43P5mqaxWEfeg87Eky0Hys24+u+ETg=,tag:EY8RAsPUUWFeC83BwiGVZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
