cronjobs:
- cmd:
  - sh
  - /workdir/pgbadger_report.sh
  - chronos-prod
  concurrencyPolicy: Forbid
  name: pg-badger-chronos-prod
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 512m
      memory: 200Mi
  schedule: 0 0 * * *
- cmd:
  - sh
  - /workdir/pgbadger_report.sh
  - chronos-prod-replica-2
  concurrencyPolicy: Forbid
  name: pg-badger-chronos-prod-replica-1
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 512m
      memory: 200Mi
  schedule: 0 0 * * *
- cmd:
  - sh
  - /workdir/pgbadger_report.sh
  - chronos-prod-replica-3
  concurrencyPolicy: Forbid
  name: pg-badger-chronos-prod-replica-2
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 512m
      memory: 200Mi
  schedule: 0 0 * * *
image:
  repository: 284983278621.dkr.ecr.eu-central-1.amazonaws.com/devops-main-pgbadger-reports
  tag: latest
serviceAccountName: arn:aws:iam::284983278621:role/tiime-prod_pgbadger_role

security-template-helm:
  networkPolicies:
    - name: pgbadger-network-policy
      enabled: true
      egress:
      rules:
        # -- Access all resources in the cluster
        - to:
            - namespaceSelector: {}
        # -- Access the port 443 from outside the cluster
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
          ports:
            # -- https port
            - port: 443
              protocol: TCP