apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
  labels:
    k8s-app: aws-node
spec:
  selector:
    k8s-app: aws-node
  ports:
    - name: metrics
      protocol: TCP
      port: 61678
      targetPort: 61678
