{{- if index .Values "argo-cd" "dex" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-dex-sso-creds
  namespace: argocd
type: Opaque
data:
  clientID: {{ .Values.github.sso.clientID }}
  clientSecret: {{ .Values.github.sso.clientSecret }}
{{- end }}
