ingress-nginx:
  controller:
    enableAnnotationValidations: false
    allowSnippetAnnotations: true
    admissionWebhooks:
      enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: tiime.tech/qos
                  operator: In
                  values:
                    - guaranteed
    tolerations:
      - key: tiime.tech/qos
        operator: Equal
        value: "guaranteed"
        effect: NoSchedule
    config:
      annotations-risk-level: "critical"
      allow-snippet-annotations: "true"
      log-format-upstream:
        '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
        "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user":
        "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":
        $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri",
        "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method":
        "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent",
        "ingress_name": "$ingress_name" }'
      use-forwarded-headers: "true"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        scrapeInterval: 60s
    minAvailable: 1
    replicaCount: 3
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 512Mi
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      externalTrafficPolicy: Local

security-template-helm:
  networkPolicies:
    - name: ingress-nginx
      enabled: true
      selector:
        # -- Only the pod with the following labels are concerned by the network policies
        matchLabels:
          app.kubernetes.io/instance: ingress-nginx
      ingress:
        rules:
          # -- Allow all traffic
          - {}
