apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: envoy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    kubernetes.io/tls-acme: "true"
spec:
  gatewayClassName: gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
{{- range $listener := .Values.listeners }}
    - name: {{ $listener.name }}
      hostname: "{{ $listener.name }}.preprod.tiime.tech"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - name: {{ $listener.tls }}
          group: ''
          kind: Secret
      allowedRoutes:
        namespaces:
          from: All       
    - name: wildcard-{{ $listener.name }}
      hostname: "*.{{ $listener.name }}.preprod.tiime.tech"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - name: {{ $listener.tls }}
          group: ''
          kind: Secret
      allowedRoutes:
        namespaces:
          from: All  
{{ end -}}
