jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:3sN0nGyfKY/W4Q92gTdOs8otil4=,iv:4TnFiRKgSnKwy0APi4hbEHxRFLhBZe/n4oEIxJ9/EbM=,tag:beEhvTaHOwBd7xV5K3W5xg==,type:str]
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:10GtcDzHo17+xonDBCFgKSQtKVw=,iv:V9MuR632LEO5kQTDe1uXUQ3sIB3jPyBpwEQ35IiDqIM=,tag:HUJL5igUPeFATI0eWemitQ==,type:str]
                client_secret: ENC[AES256_GCM,data:XDpDfdg6Eccl/A2TvrCEuMeTIOALyJ/2PP4rUrY8Yjk/+qTbGSvVdg==,iv:UMGKL+ut3d/zA3l+o9vbYbevaYY5smWItH6X+qPRDXs=,tag:kr7v5hO8QUxdZZWZlN939Q==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:gqRDfRjEqrQd9hzrEh74/kwPjTJksdmCFhKwEzCv0L6KpHH6qqYCcNUQ3HJp8LVH36AlIc1msiA=,iv:PZlk4t5QO8favYLa+4bat85hxDcXiO9HAk1rCBKwUh8=,tag:CdraIJEFG5tbrw8qPncFuw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-11-27T14:25:03Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgEIAskdnC4+Kj6su99HYeS8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3EbnTooBhz1DbjPZAgEQgDv3u/Zwb9tPXvfNJUQRqYJuhjRed82oPOdjXlwXPzyZFaGQcq4KBwK+PWkZHR1cCv9mw/PtAqDcycFTFA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-27T14:25:03Z"
    mac: ENC[AES256_GCM,data:dxYt4kp8dWerfLFA1LpvCqfAhmt88PaCQqMQsqNdTR1y61sMn5JhOmx/b2BsOqOngtFn4aEzpW5eKJKFAgivd0q97nbetLfSIqSsMP3g5ZzdYkbLghEJAV70IGJ07eM8k9GEVWhepHoGwlywHraLeq0UdlrbkAqWj1nmBpCHLTI=,iv:vvoZ3O0t1Co9owc0ZRRY5kJtGJSVC5gBqfXIih/ytXg=,tag:2TgJWKExXqYbJPXrnPvLjw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
