aws-load-balancer-controller:
  resources:
    requests:
      cpu: 5m
      memory: 128Mi
    limits:
      memory: 128Mi
  serviceMonitor:
    enabled: true
  tolerations:
    - key: "arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
