rabbitmq-cluster-operator:
  clusterOperator:
    networkPolicy:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
  msgTopologyOperator:
    networkPolicy:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    resources:
      limits:
        cpu: 300m
        memory: 384Mi
      requests:
        cpu: 200m
        memory: 256Mi
