listeners:
- name: chronos-review-amaranth
  tls: chronos-amaranth-tls
- name: chronos-review-black
  tls: chronos-black-tls
- name: chronos-review-blue
  tls: chronos-blue-tls
- name: chronos-review-brown
  tls: chronos-brown-tls
- name: chronos-review-cerfrance
  tls: chronos-cerfrance-tls
- name: chronos-review-cinereous
  tls: chronos-cinereous-tls
- name: chronos-development
  tls: chronos-development-tls
- name: chronos-review-green
  tls: chronos-green-tls
- name: chronos-review-grey
  tls: chronos-grey-tls
- name: chronos-review-indigo
  tls: chronos-indigo-tls
- name: chronos-review-lavender
  tls: chronos-lavender-tls
- name: chronos-review-onyx
  tls: chronos-onyx-tls
- name: chronos-review-orange
  tls: chronos-orange-tls
- name: chronos-review-pink
  tls: chronos-pink-tls
- name: chronos-review-purple
  tls: chronos-purple-tls
- name: chronos-review-red
  tls: chronos-red-tls
- name: chronos-staging
  tls: chronos-staging-tls
- name: chronos-review-teal
  tls: chronos-teal-tls
- name: chronos-testing
  tls: chronos-testing-tls
- name: chronos-review-white
  tls: chronos-white-tls
- name: chronos-review-yellow
  tls: chronos-yellow-tls
- name: chronos-review-leafy
  tls: chronos-leafy-tls
- name: chronos-review-pistachio
  tls: chronos-pistachio-tls
