prometheus-cloudwatch-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 380Mi
    limits:
      memory: 380Mi
  config: |-
    region: eu-west-1
    period_seconds: 60
    metrics:
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: DatabaseConnections
      aws_namespace: AWS/RDS
      aws_statistics:
      - Maximum
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: FreeStorageSpace
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: FreeableMemory
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: CPUUtilization
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: ReadIOPS
      aws_namespace: AWS/RDS
      aws_statistics:
      - Sum
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: WriteIOPS
      aws_namespace: AWS/RDS
      aws_statistics:
      - Sum
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: ReadLatency
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: WriteLatency
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: ReadThroughput
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: WriteThroughput
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: CPUCreditUsage
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: CPUCreditBalance
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: DiskQueueDepth
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: NetworkTransmitThroughput
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: NetworkReceiveThroughput
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: EBSByteBalance%
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - DBInstanceIdentifier
      aws_metric_name: EBSIOBalance%
      aws_namespace: AWS/RDS
      aws_statistics:
      - Average
    - aws_dimensions:
      - ReplicationInstanceIdentifier
      - ReplicationTaskIdentifier
      aws_metric_name: RunCounter
      aws_namespace: AWS/DMS
      aws_statistics:
      - Average
    - aws_dimensions:
      - ReplicationInstanceIdentifier
      - ReplicationTaskIdentifier
      aws_metric_name: CDCThroughputRowsSource
      aws_namespace: AWS/DMS
      aws_statistics:
      - Average
    - aws_dimensions:
      - ReplicationInstanceIdentifier
      - ReplicationTaskIdentifier
      aws_metric_name: CDCLatencySource
      aws_namespace: AWS/DMS
      aws_statistics:
      - Average
    - aws_dimensions:
      - ReplicationInstanceIdentifier
      - ReplicationTaskIdentifier
      aws_metric_name: CDCLatencyTarget
      aws_namespace: AWS/DMS
      aws_statistics:
      - Average
    - aws_dimensions:
      - ReplicationInstanceIdentifier
      - ReplicationTaskIdentifier
      aws_metric_name: SwapUsage
      aws_namespace: AWS/DMS
      aws_statistics:
      - Average
    - aws_dimensions:
      - ReplicationInstanceIdentifier
      - ReplicationTaskIdentifier
      aws_metric_name: CDCIncomingChanges
      aws_namespace: AWS/DMS
      aws_statistics:
      - Average
  prometheusRule:
    enabled: true
    rules:
    - alert: Database-CPU-High-Utilisation
      annotations:
        message: The Database cpu utilisation during the last 1 hour is higher than
          90%.
      expr: aws_rds_cpuutilization_average > 90
      for: 1h
      labels:
        severity: warning
    - alert: KubeAPIErrorBudget < 80 %
      annotations:
        summary: The API server error budget < 80 %
      expr: 100 * (apiserver_request:availability30d{verb="all", cluster=""} - 0.990000) < 0.80
      for: 1m
      labels:
        severity: critical
    - alert: PostgresqlEBSByteBalanceAlmostConsumed
      annotations:
        summary: Postgresql EBSByteBalance almost fully used
      expr: last_over_time(aws_rds_ebsbyte_balance__average{dbinstance_identifier!~"chronos-prod-replica-2|chronos-prod"}[15m])
        <= 20
      for: 2h
      labels:
        severity: warning
    - alert: PostgresqlEBSByteBalanceAlmostConsumedCritical
      annotations:
        summary: Postgresql EBSByteBalance almost fully used
      expr: last_over_time(aws_rds_ebsbyte_balance__average{dbinstance_identifier=~"chronos-prod-replica-2|chronos-prod"}[15m])
        <= 20
      for: 10m
      labels:
        severity: critical
    - alert: PostgresqlEBSIOBalanceAlmostConsumed
      annotations:
        summary: Postgresql EBSIOBalance almost fully used
      expr: last_over_time(aws_rds_ebsiobalance__average{dbinstance_identifier!~"chronos-prod-replica-2|chronos-prod"}[15m])
        <= 20
      for: 2h
      labels:
        severity: warning
    - alert: PostgresqlEBSIOBalance
      annotations:
        summary: Postgresql EBSIOBalance almost fully used on critical databases
      expr: last_over_time(aws_rds_ebsiobalance__average{dbinstance_identifier=~"chronos-prod-replica-2|chronos-prod"}[15m])
        <= 20
      labels:
        severity: critical
    - alert: DatabaseOutOfStorage
      annotations:
        summary: Storage size is approaching the maximum storage threshold. Increase the maximum storage threshold.
      expr: last_over_time(aws_rds_free_storage_space_average{dbinstance_identifier=~"data-.*|chronos-.*"}[5m]) / 1000000000 < 300
      for: 3h
      labels:
        severity: warning
    - alert: DatabaseOutOfStorageCritical
      annotations:
        summary: Storage size is approaching the maximum storage threshold. Increase the maximum storage threshold.
      expr: last_over_time(aws_rds_free_storage_space_average{dbinstance_identifier=~"data-.*|chronos-.*"}[5m]) / 1000000000 < 100
      for: 30m
      labels:
        severity: warning
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::990075099095:role/preprod_cloudwatch_exporter_role
  serviceMonitor:
    enabled: true
    interval: 60s
    timeout: 30s
