gotenberg:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  logging:
    format: json
  metrics:
    serviceMonitor:
      enabled: true

security-template-helm:
  networkPolicies:
    - name: gotenberg-network-policy
      enabled: true
      egress:
        rules:
          # -- Access to ingress from outside the cluster
          - ports:
              # -- https port
              - port: 443
                protocol: TCP
            to:
              - ipBlock:
                  cidr: 0.0.0.0/0
          # -- Access to all pod in the same namespace
          - to:
              - podSelector: {}
          # -- Access to all pod
          - to:
              - namespaceSelector: {}
      ingress:
        rules:
          # -- Allow all pod in the same namespace
          - from:
              - podSelector: {}
          # -- Allow all pod to port 80 (http)
          - from:
              - namespaceSelector: {}
            ports:
              # -- http port
              - port: 3000
                protocol: TCP
