{{- range $cron := .Values.backup.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cron.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: {{ $cron.concurrencyPolicy }}
  schedule: {{ $cron.schedule }}
  suspend: {{ $cron.suspend | default false }}
  jobTemplate:
    spec:
      {{- if hasKey $cron "backoffLimit" }}
      backoffLimit: {{ $cron.backoffLimit }}
      {{- end }}
      template:
        metadata:
          annotations:
            karpenter.sh/do-not-disrupt: "true"
        spec:
          priorityClassName: cronjob-pc
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
                      - key: karpenter.sh/capacity-type
                        operator: In
                        values:
                          - on-demand
          containers:
            - name: {{ $cron.name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              command: {{ $cron.command | toYaml |nindent 16 }}
              imagePullPolicy: Always
              volumeMounts:
{{- if ($cron.ephemeral) }}
                - name: backup-data
                  mountPath: /data
{{- end}}
                - name: persistent-storage
                  mountPath: /tiime-ops/
              env:
                - name: ONEPASSWORD_PWD
                  value: {{ $.Values.onePassword.password }}
                - name: ACCESS_KEY
                  value: {{ $.Values.onePassword.access_key }}
                - name: MAIL
                  value: {{ $.Values.onePassword.mail }}
                - name: DEVICE_UUID
                  value: {{ $.Values.onePassword.device_uuid }}
                - name: SERVICE_ACCOUNT_TOKEN
                  value: {{ $.Values.onePassword.token }}
              {{- if hasKey $cron "resources" }}
              resources:
              {{- toYaml $cron.resources | nindent 18 }}
              {{- end }}
          restartPolicy: OnFailure
          serviceAccountName: {{ $.Release.Name }}
          volumes:
{{- if ($cron.ephemeral) }}
            - name: backup-data
              ephemeral:
                volumeClaimTemplate:
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    storageClassName: gp3
                    volumeMode: Filesystem
                    resources:
                      requests:
                        storage: {{ $cron.storage | default "100Gi" }}
{{- end }}
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: {{ $.Release.Name }}-s3-claim
---
{{- end }}
