apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-s3-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany
  mountOptions:
    - region eu-west-3
    - allow-other
    - uid=101
    - gid=101
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: tiime-ops
