argocd-template-helm:
  argoApps:
    cni-metrics-helper:
      appsNameOverride: cni-metrics-helper
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/cni-metrics-helper"
          targetRevision: "main"
          helm:
            releaseName: cni-metrics-helper
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    fluentbit:
      appsNameOverride: fluentbit
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/fluentbit"
          targetRevision: "main"
          helm:
            releaseName: fluent-bit
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: fluentbit

    k8s-monitoring:
      appsNameOverride: k8s-monitoring
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/grafana-k8s-monitoring"
          targetRevision: "main"
          helm:
            releaseName: k8s-monitoring
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    loki-archive:
      appsNameOverride: loki-archive
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/loki-archive"
          targetRevision: "main"
          helm:
            releaseName: loki-archive
        destination:
          namespace: loki-archive
        syncPolicy:
          automatedEnableDefaultConfig: false

    pg-badger:
      enabled: false
      finalizer: true
      appsNameOverride: pg-badger
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/pg-badger"
          targetRevision: "main"
          helm:
            releaseName: pg-badger
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: pg-badger

    prometheus-cloudwatch-exporter:
      enabled: false
      finalizer: true
      appsNameOverride: prometheus-cloudwatch-exporter
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/prometheus-cloudwatch-exporter"
          targetRevision: "main"
          helm:
            releaseName: prometheus-cloudwatch-exporter
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    prometheus-crd:
      appsNameOverride: prometheus-crd
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/prometheus-crd"
          targetRevision: "main"
          helm:
            releaseName: prometheus-crd
        syncPolicy:
          automatedEnableDefaultConfig: true
          syncOptions:
            - Replace=true
            - Validate=true
            - CreateNamespace=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
        destination:
          namespace: metrology

    prometheus-elasticsearch-exporter:
      enabled: false
      finalizer: true
      appsNameOverride: prometheus-elasticsearch-exporter
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/prometheus-elasticsearch-exporter"
          targetRevision: "main"
          helm:
            releaseName: prometheus-elasticsearch-exporter
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    prometheus-ethtool-exporter:
      enabled: false
      finalizer: true
      appsNameOverride: prometheus-ethtool-exporter
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        source:
          chart: prometheus-ethtool-exporter-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0"
          helm:
            releaseName: prometheus-ethtool-exporter
            valueFiles:
              - "values.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    prometheus-rds-exporter:
      enabled: false
      finalizer: true
      appsNameOverride: prometheus-rds-exporter
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/prometheus-rds-exporter"
          targetRevision: "main"
          helm:
            releaseName: prometheus-rds-exporter
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    promtail:
      appsNameOverride: promtail
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/promtail"
          targetRevision: "main"
          helm:
            releaseName: promtail
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    sentry:
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/sentry"
          targetRevision: "main"
          helm:
            releaseName: hub
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: sentry

    uptimerobot-operator:
      appsNameOverride: uptimerobot-operator
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/uptimerobot-operator"
          targetRevision: "main"
          helm:
            releaseName: uptimerobot-operator
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: operator

    github-actions-exporter:
      enabled: false
      finalizer: true
      appsNameOverride: github-actions-exporter
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/github-actions-exporter"
          targetRevision: "main"
          helm:
            releaseName: github-actions-exporter
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology

    dora-exporter:
      enabled: false
      finalizer: true
      appsNameOverride: dora-exporter
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/dora-exporter"
          targetRevision: "main"
          helm:
            releaseName: dora-exporter
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: metrology
