argocd-template-helm:
  default:
    spec:
      project: default
      syncPolicy:
        automated:
          prune: "true"
          selfHeal: "true"
          allowEmpty: "true"
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff: 
            duration: 5s
            factor: 2
            maxDuration: 3m
  argoApps:
    argo-rollout:
      appsNameOverride: argo-rollout
      enabled: true
      finalizer: false
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: default
        source:
          repoURL: "https://github.com/dromadaire54/test-poc-applicationset.git"
          path: "./k8s/middlewares/argo-rollout"
          targetRevision: "master"
          helm:
            releaseName: argo-rollout
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: argo-rollout