argocd-template-helm:
  argoApps:
    karpenter:
      appsNameOverride: karpenter
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/karpenter"
          targetRevision: "main"
          helm:
            skipCrds: true
            releaseName: karpenter
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: karpenter


    karpenter-crd:
      appsNameOverride: karpenter-crd
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/karpenter-crd"
          targetRevision: "main"
          helm:
            releaseName: karpenter-crd
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: karpenter

    keda:
      appsNameOverride: keda
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/keda"
          targetRevision: "main"
          helm:
            releaseName: keda
        syncPolicy:
          syncOptions:
            - ServerSideApply=true
          automatedEnableDefaultConfig: true
        destination:
          namespace: keda

    kube-downscaler:
      appsNameOverride: kube-downscaler
      enabled: false
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: ops
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops.git"
          path: "./k8s/middlewares/kube-downscaler"
          targetRevision: "main"
          helm:
            releaseName: kube-downscaler
        syncPolicy:
          automatedEnableDefaultConfig: false
        destination:
          namespace: kube-downscaler
