flink-kubernetes-operator:
  metrics:
    port: 9999
  prometheus:
    enableReporting: true
  operatorPod:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                    - flink
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "flink"
        effect: "NoSchedule"