networkPolicies:
- name: cert-manager
  namespace: ingress
  enabled: true
  selector:
    # -- Only the pod with the following labels are concerned by the network policies
    matchLabels:
      app.kubernetes.io/instance: cert-manager
  egress:
    rules:
      # -- Access to the pod which renew the certificate (the pod has a specific labels)
      - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              acme.cert-manager.io/http01-solver: "true"
        # -- The certmanager call the port pod on the port 8089 to renew teh certificates
        ports:
        - port: 8089 # acme port (renewing certificate)
          protocol: TCP
      # -- Access to http and https to outside the cluster
      - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        ports:
        - port: 443 # https
          protocol: TCP
        - port: 80 # http
          protocol: TCP
      # -- Access to kube dns pod on port 53 UDP
      - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: coredns
        ports:
          # -- dns port
          - port: 53
            protocol: UDP
  ingress:
    rules:
      # -- Allow to metrics port from metro namespace
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: metro
        ports:
        # -- metric cert-manager
        - port: 9402
          protocol: TCP
      # -- Allow to certmanager webhook from outside the cluster
      - from:
        - ipBlock:
            cidr: 0.0.0.0/0
        ports:
        # -- certmanager webhook port
        - port: 10250
          protocol: TCP
