kyverno:
    imagePullSecrets:
        kyvernodockerhub:
            registry: ENC[AES256_GCM,data:WrLwDLDOTTtn,iv:duaeySe7MZ3B8H7U7LpcZo11Da1jI/CYIyhSVj3Iqmo=,tag:kC0epM//KgC31Ebd/zM0YA==,type:str]
            username: ENC[AES256_GCM,data:f+X7TGTUPC8jB4IqWw==,iv:RHS0gmeMmVRqW5g4aGK4mG14nrIl2FTijQ+WT5w7Hq4=,tag:+xqQJhYLF/ymy72SWddaNw==,type:str]
            password: ENC[AES256_GCM,data:4ka43LImw9aBamLYPg5TZfrLgyDGsgIR/w4WkUCl58Uy78Z/,iv:F1o9zqJZQY2NJ/YQ2+AiXgxMFE6FxiHJhdFspe9/V7A=,tag:KWjG/E1MhoMiq7HP58ONLg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-12-02T09:51:12Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgFLMqCiZyBYh5iK7LTV+nNQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMxiatrB46y+aOZ2jLAgEQgDuw8ArVKn9YVGrgn3K5Y1um2DpOuLLQqnKjKQoSOZLuaSaaA3FsvAgNCrD4WAZ1GPP1YNrEJPgENeh4qQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-02T09:51:13Z"
    mac: ENC[AES256_GCM,data:63wW9ppDp+EnfTigIwrsN+qQY8GTsZKS9EOzqxKY7jKRrs1+JvC/AkkupJWW92/bbVbvwnGtut7ZfCtpK3yi8R/BNjvKDwaFXGOi+Z9pmfcdCju+l3bd+yN7LMQZ1u7UoeCY8aFoEQCyWdVvRoa2Fc2U9mFwD2AVIZGmJtdYCfE=,iv:qEyp6oIYNWcudlwJGFsnKFHL6uPK9SV6s0+XvkCCsIc=,tag:Ym2xzQkacaY+ewnnOnGjsw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
