kyverno:
    imagePullSecrets:
        kyvernodockerhub:
            registry: ENC[AES256_GCM,data:CRmzE84zYWku,iv:WSaeK4ZMSg+c84NOC6VZHN3BvBzF4GUKP2BiocZt25o=,tag:AnbYq9JPH09n3e3CPMbr+w==,type:str]
            username: ENC[AES256_GCM,data:A7lDd357tefKZ8xFfQ==,iv:0biq7ql04rpgVAYiMWd+ifKmXsxvM7ZqdTDOizl3XZQ=,tag:0CPZhs3S4VA11hUFh0lD3w==,type:str]
            password: ENC[AES256_GCM,data:+3RqgR5tKcApstlumoTaD0m0mxA/Gk6g/FkIVeTbqjUZSo+O,iv:1Nx96xdI+h2MkLaEhQ53hu+p7lSER96rXeGZdv3gmT4=,tag:dh9QQpHYm90fTyr/sZzZAA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-12-02T09:48:05Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgHdIILDYLmQcRKrXIoSH1fMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpM+qCQm8eYKrWn7LAgEQgDtVpsV47bb3LWuGyQAe42cU+7dpjR2ZnMs4+AA8mqMAo0XOScEeYOAV/kllR3XQwfkwkGl8E7bTA7BnXg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-02T09:48:06Z"
    mac: ENC[AES256_GCM,data:shiE9X8xD6+JCRs/kq9W2ZfOMcPSUui9bOLe+w6ks69AA7+T/OLgCeBb9bZ/8G0JWv4mLAxKcsVoi4GyoNiodIe0Ln5LsuDTcqrLmFjUp5lvRfqNW4Vf45clAi8J25Hh2LZsCyixudnIMVBWfj6UbglWVQz5WGtM/xVC5MlLFic=,iv:KbYIp593sjlYkxXmKwQaxZg4D9tAVkmGm+2ONfMTlRY=,tag:lY58AhxKVZPsj4lUPvHkrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
