pgbouncer: 
  enabled: false
  replicas: 2

postgres_exporter:
  enabled: false

prometheus-postgres-exporter:
  config:
    datasourceSecret:
      name: postgres-exporter-database-secret
      key: databaseURI

  extraEnvs:
    - name: PG_EXPORTER_EXTEND_QUERY_PATH
      value: "/extended-queries/queries.yaml"

  extraVolumes:
    - name: extended-queries
      configMap:
        name: postgres-exporter-database-extended-queries

  extraVolumeMounts:
    - name: extended-queries
      mountPath: /extended-queries
      readOnly: true

  serviceMonitor:
    enabled: true

monitoring:
  enabled: false

alerting:
  enabled: true
  threshold: 5