  # -- configuration for the database, these values are required
database:
  # -- hostname of the database
  host: postgresql.test.com
  # -- port of the database
  port: 5432
  # -- username of the database
  user: postgres
  # -- name of the database
  name: database
  # -- password of the database, this value should be stored in a sops secret
  password: password

# -- configuration for the hooks to execute on the database, these values are not required
hooks:
  # -- configuration for any hooks, these hooks are executed on the database
  example:
    # -- weight of the hook, this is used to determine the order of execution of the hooks
    weight: 1
    # -- execution of the hook, this is used to determine when the hook is executed
    execution: "pre-upgrade"
    # -- delete policy of the hook, this is used to determine when the hook is deleted
    deletePolicy: "before-hook-creation"
    # -- resource limits/requests for the hook
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  # -- configuration for the teleport hook
  # -- this hook will create teleport users (db_readonly, db_readwrite, db_superuser) and grant it access to the database
  teleport:
    # -- enable the teleport hook
    enabled: false
  # -- configuration for the replication slots hook
  # -- this hook will create replication slots for the database
  replicationSlots:
    # -- enable the replication slots hook
    enabled: false
    # -- resource limits/requests for the replicationSlots hook
    slots:
      # -- name of the replication slot
      - name: "example_slot"
        # -- enable the replication slot
        enabled: false

# -- configuration for pgbouncer
pgbouncer: 
  # -- enable pgbouncer
  enabled: false
  # -- number of replicas for pgbouncer
  replicas: 2

# -- configuration for postgres_exporter
postgres_exporter:
  # -- enable postgres exporter
  enabled: false

# -- configuration for the postgres exporter dependency
prometheus-postgres-exporter:
  config:
    datasourceSecret:
      name: postgres-exporter-database-secret

# -- Create default prometheus rule for database with some parameter
alerting:
  # -- Enabled the database alerting @default true
  enabled: true
  # -- The threshold storage space to trigger an alert 
  threshold: 300