loki:
    loki:
        tenants:
            - name: ENC[AES256_GCM,data:/i9V8d++,iv:SkOKoDR7T4JC582ZuCZqflWVmJQYOKzNtFYws0nYxVY=,tag:j26uO4VwCVf2LnfJlcxPBQ==,type:str]
              password: ENC[AES256_GCM,data:K0Qo/lmm362xXN4v0ZZt6ph23WR8qATwgkg3odod9YbwbH7d0Q==,iv:MdZ+EabiveJSjho1hPpB9hQfezdVNoOotUD3YekdWxo=,tag:T3YcLvexWrRyVnA5YbpaGg==,type:str]
              passwordUnencoded: ENC[AES256_GCM,data:wxew6VjNtAukO4qMWwzmX6FpfWpR3I4KSaVNuQFxteA=,iv:fvM6wOxY3mhj1/8xBntgh00X4Z+/KtRNgjZ4p9eBQmQ=,tag:OJAEGNSSc1vlDCrgpVNuUg==,type:str]
        storage:
            s3:
                accessKeyId: ENC[AES256_GCM,data:2lNAvz+LvkkV/ShdEs1znTilklg=,iv:MCrkhifLeZHbmamSSF87fWbS1d1GIdiRu1LfJ2iGoNI=,tag:iQ5DFwF9Pem/hyeXeZNApg==,type:str]
                secretAccessKey: ENC[AES256_GCM,data:W6QpBHP4Xf6KgagEhLbfqWa+RuGdjvCt4H5brMs/07m6+6e1R8lSCg==,iv:jICJqzG6xKQO1zeXyUSOTfV4873hcw/oBFhEc5HsqVQ=,tag:7uKp3bUbQfCiSxwEjPwabw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2025-06-18T13:00:22Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgEIpmK3H+zdSdUtgLVydCxSAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJwGAiJqDMFh6CRbmAgEQgDuKjZRuk+vnaUOPzX91ObRf4SYBXrNhoUaUj5yStS/84RhCBRKPCmYLkDjZjPdXc8IdPZ5v3+4ZNfcALQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-18T13:00:22Z"
    mac: ENC[AES256_GCM,data:XWgIjk6+WvOtOaiK3B/mfCSQSZ0R6queg5HsE+gFowIjpbh3mFCYnXX9Pt35MOQLIFNkJ5We7FVsH6Y3qwfCfFnibIqc+rvrST0kfuZtP3Q6sn/379X2XiC5RqAkthOJXHrSgmr3MGy/uG073PV8T6JuZpsnKZrUGibHIfRtUs8=,iv:UhocTv8ZW10HwJg1kcxNZdMSB+eMt5rTzq14zAvtFLo=,tag:vcWdsQ1umTIypkPq8apT2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
