argocd-template-helm:
  argoApps:
    karpenter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-prod.yaml"

    karpenter-crd:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"

    keda:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false
    
    kube-downscaler:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
