argocd-template-helm:
  argoApps:
    chronos-cleanup-databases:
      enabled: true
      spec:
        source:
          helm:
            parameters:
              - name: serviceAccountName
                value: 'arn:aws:iam::284983278621:role/tiime-prod_chronos_cleanup_databases_role'
        syncPolicy:
          automatedEnableDefaultConfig: false
    kyverno:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "values-prod.yaml"
              - "secrets://values-secret-prod.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false


    kyverno-policy-reporter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
