argocd-template-helm:
  argoApps:
    cni-metrics-helper:
      enabled: true

    fluentbit:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-prod.yaml"
              - "secrets://values-secret-prod.yaml"

    k8s-monitoring:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "values-prod.yaml"
              - "secrets://values-secret-prod.yaml"
    
    loki-archive:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "secrets://secrets.yaml"

    pg-badger:
      enabled: false
      spec:
        source:
          helm:
            valueFiles:
              - "values-prod.yaml"
              - "secrets://values-secret-prod.yaml"

    prometheus-cloudwatch-exporter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-prod.yaml"

    prometheus-crd:
      enabled: true

    prometheus-elasticsearch-exporter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-prod.yaml"
              - "secrets://values-secret-prod.yaml"
    
    prometheus-ethtool-exporter:
      enabled: true

    prometheus-rds-exporter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-prod.yaml"

    promtail:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "secrets://secrets.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    sentry:
      appsNameOverride: sentry
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values-prod.yaml"
              - "secrets://values-secret-prod.yaml"
        syncPolicy:
          automatedEnableDefaultConfig: false

    uptimerobot-operator:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "values.yaml"
              - "secrets://values-secret-prod.yaml"

    github-actions-exporter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "secrets://secrets-prod.yaml"
              - "values-prod.yaml"

    dora-exporter:
      enabled: true
      spec:
        source:
          helm:
            valueFiles:
              - "secrets://values-secret-prod.yaml"
              - "values-prod.yaml"
              - "values.yaml"
