apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
      nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.dora.ingress.whitelist.range }}
  labels: 
    {{ include "dora.labels" $ | indent 4 }}
spec:
  tls:
    - hosts:
        - {{ $.Values.dora.siteUrl }}
      secretName: {{ $.Release.Name }}
  rules:
    - host: {{ $.Values.dora.siteUrl }}
      http:
        paths:
          - path: /api/github
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Release.Name }}"
                port:
                  number: 8090
          - path: /api/jira
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Release.Name }}"
                port:
                  number: 8090
