kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  labels: 
    {{ include "dora.labels" $ | indent 4 }}
type: Opaque
data:
  github-token: {{ .Values.github_token | b64enc }}
