
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  labels: 
    {{ include "dora.labels" $ | indent 4 }}
spec:
  endpoints:
  - port: metrics
    interval: 60s
  selector:
    matchLabels:
      {{ include "dora.labels" $ | indent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
