{{- if hasKey .Values "hooks"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database.hooks.configmapName" . }}
  labels: {{- include "database.hooks.labels" $ | nindent 4}}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/resource-policy": keep
data:
{{- if (.Values.hooks.teleport).enabled }}
  teleport.sql: |
{{ $.Files.Get "files/hooks/teleport.sql" | indent 4  }}
{{- end}}
{{- if (.Values.hooks.replicationSlots).enabled }}
  replication_slots.sql: |
{{- tpl ($.Files.Get "files/hooks/replication_slots.sql") $ | indent 4  }}
{{- end}}
{{- end}}