promtail:
    config:
        clients:
            - url: ENC[AES256_GCM,data:TOTEQvhwNQwtB2PNr/AXL+0Gf2D/or3Xl0koMm6/eWZ9IG3QkgtBhWg/1NbY8i7ZJr0=,iv:D//xtNrtJwmlQDKUnqbjiEp/eGgOWzukgiGXN1954Bw=,tag:fKDDWBazJETERU7Y8K8BPA==,type:str]
              basic_auth:
                username: ENC[AES256_GCM,data:DO3xdOWn,iv:gkOG9H2UrZTeeBhfC0i4x4IEcmC6EBuQoTl6eV27A0w=,tag:N2TBVDrP/K7wyHl7pqb2pw==,type:str]
                password: ENC[AES256_GCM,data:Kub5xgOPCBg4137B99rzMRHT84dcOSII7XiAe3K3+gTjORnsK82MggB9pZjsE+q3caup9Q9rWsZKG3mhkfwLaj/wsS0VHTby9/QSz6VAp+w7HFlRNv3rV+UL1baEtckmLbXzFpfV2sZeikwgsBCWc+7NjALEXwV+wD2QObwI9A5gUhNW3x8VZ9kZAmaklb2aIuLOAWgT1LCTEuTv2SF/Dc8tXiHN9ZCZHIU3DBxvzOkRyIXPIQweDKVBlWIZeDxt,iv:Jt9KMuS+LWmqJoNTrs+BYHJfEr18pJmWNERtm65RYXM=,tag:Xi0J+yxAeqvdDHtl/JqKrg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2025-01-23T08:19:59Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgGK1cYX35IyJk9LA8Xl1SmlAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUx8HrMcJjXMMLCFJAgEQgDtjlfI6NIqyVnEdF7Y72Eb9M4BKmJ3IhywcsL/I8Mv5ezZi3HzzCoIxptV/GEY9hUONzUmralkUzJOo1w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-23T08:20:00Z"
    mac: ENC[AES256_GCM,data:KQW5zm7pk4nHCJgKhZP+pqf0eDAK6qeY/gWUNY8onO5N5753JKPH1RClybh33WaXQ57UXLL+O+z71U/5xDheuZTSqTY1ICx4S9E5ab0obYnhPHCL+uvU5XISrpMIiodeBdYVtUoCKNqwnSmDpUdEuqOSlHlc6fkD3TiVk8WLFEc=,iv:cXh58YFEmiKTh4e+8XeEDkaHhcMAUG5iUUvaSj2ipgY=,tag:UbMvt1Pfwy5OYF06FNvveQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
