{{- if not ($.Values.global.maintenance.enabled) -}}
{{- range $cronjobName, $cronjob := .Values.cronjobs }}
{{ if or (not (has $cronjobName $.Values.cronjobsSuspended)) (not ($cronjob.deletedIfSuspended | default false)) }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name:  {{ include "cronjob.name" (dict "name" $cronjobName )}}
  labels:
    {{ $.Values.global.organization }}/team: {{ $cronjob.team }}
    {{- include "cronjob.labels" $ | nindent 4 }}
spec:
  timeZone: {{ $cronjob.timezone | default "Europe/Paris" | quote }}
  schedule: {{ $cronjob.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: {{ $cronjob.concurrencyPolicy }}
  suspend: {{ has $cronjobName $.Values.cronjobsSuspended }}
  jobTemplate:
    metadata:
      labels:
        # label used to monitor cronjob execution in Grafana.
        {{ $.Values.global.organization }}/cronjob: {{ $cronjobName }}
        {{ $.Values.global.organization }}/team: {{ $cronjob.team }}
        {{- include "cronjob.labels" $ | nindent 8 }}
    spec:
      backoffLimit: {{ $cronjob.backoffLimit | default 0 }}
      {{- if hasKey $cronjob "activeDeadlineSeconds" }}
      activeDeadlineSeconds: {{ $cronjob.activeDeadlineSeconds }}
      {{- end }}
      template:
        metadata:
          labels:
            {{- include "cronjob.labels" $ | nindent 12 }}
            # label used to monitor cronjob execution in Grafana.
            {{ $.Values.global.organization }}/cronjob: {{ $cronjobName }}
            {{ $.Values.global.organization }}/team: {{ $cronjob.team }}
            {{ $.Values.global.organization }}/component: {{ $cronjobName }}
            {{ $.Values.global.organization }}/escloud-log-export: "true"
          annotations:
            {{ $.Values.global.organization }}/checksum-config: {{ $.Values | toString | sha256sum }}
            karpenter.sh/do-not-disrupt: "true"
        spec:
          priorityClassName: cronjob-pc
          restartPolicy: Never
          containers:
          - name: {{ $cronjobName }}
            {{- if hasKey $cronjob "image" }}
            image: {{ $cronjob.image }}
            {{- else }}
            image: "{{ $.Values.global.images.php.repository }}:{{ $.Values.global.images.php.tag }}"
            {{- end }}
            {{- if hasKey $cronjob "command" }}
            command:
              {{- range $cronjob.command }}
              - {{ .  }}
              {{- end }}
            args:
{{ toYaml $cronjob.args | indent 14 }}
            {{- else }}
            args:
              - "php"
              - "bin/console"
{{ toYaml $cronjob.args | indent 14 }}
            {{- end }}
            env:
              - name: CRONJOB_SCHEDULE
                value: "{{ $cronjob.schedule }}"
              {{- include "tiime-core.new_relic_config" (dict "newRelicSplitEnabled" $.Values.newRelicSplitEnabled "subProject" "cronjob" "Release" $.Release) | nindent 14 }}
              {{- include "tiime-core.deployment.env" (dict "pgbouncer" true "root" $) | nindent 14 }}
              {{- include "tiime-core.php.memory_env" $cronjob.resources.limits.memory  | indent 14 }}
            envFrom:
            {{- if $cronjob.secretRef }}
            {{- range $secretRef := $cronjob.secretRef }}
            - secretRef:
                name: {{ $secretRef }}
            {{- end }}
            {{- else }}
            - secretRef:
                name: {{ $.Release.Name }}
            - secretRef:
                name: {{ $.Release.Name }}-env-common
            {{- end }}
            resources: {{- toYaml $cronjob.resources | nindent 16 }}
            volumeMounts:
              {{- if $cronjob.volumeMounts }}
              {{- toYaml $cronjob.volumeMounts | nindent 14 }}
              {{- end }}
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          serviceAccountName: {{ $.Release.Name }}
          {{- if hasKey $cronjob "extraSpec" }}
          {{ $cronjob.extraSpec | toYaml | nindent 10 }}
          {{- else }}
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                    - arm64
          {{- end }}
          volumes:
            {{- if $cronjob.volumes }}
            {{- toYaml $cronjob.volumes | nindent 10 }}
            {{- end }}
...
{{- end }}
{{- end }}
{{- end }}