{{- range $name, $val := .Values.aws }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-{{ $name }}-credentials-sync
  namespace: argocd
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: argocd-server
          volumes:
            - emptyDir:
                medium: Memory
              name: token

          initContainers:
            - image: amazon/aws-cli:latest
              name: get-token
              imagePullPolicy: IfNotPresent
              env:
                - name: REGION
                  value: {{ $val.region | default "eu-central-1" }}
              command:
                - /bin/sh
                - -ce
                - aws ecr get-login-password --region ${REGION} > /token/ecr-token
              volumeMounts:
                - mountPath: /token
                  name: token

          containers:
            - name: create-secret
              image: bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SECRET_NAME
                  value: ecr-credentials
                - name: ECR_REGISTRY
                  value: {{ $val.registry | required "The aws registry is required" }}
              command:
                - /bin/bash
                - -ce
                - |-
                  cat <<EOF | kubectl apply -f -
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: argocd-ecr-{{ $name }}-helm-credentials
                    namespace: argocd
                    labels:
                      argocd.argoproj.io/secret-type: repository
                  stringData:
                    username: AWS
                    password: $(</token/ecr-token)
                    enableOCI: "true"
                    name: "ECR"
                    type: "helm"
                    url: "{{ $val.registry }}"
                  EOF
              resources:
                limits:
                  memory: 100Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              volumeMounts:
                - mountPath: /token
                  name: token
---
{{- end }}
