uptimerobot-operator:
    uptimeRobotApiKey: ENC[AES256_GCM,data:4Z94CnoD1xFZtnS8Ml94QmJjiWXcAkowK7eVMKPI5BF2,iv:yKcK7Z0u6WfhYNaGCoc3Lgkoked7MjdVr5XCSHsRECE=,tag:lOD3RVJNmfrddMhKOCJ13w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-11-27T14:26:03Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgHhAGZcCONtvzj3q8/sInbsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmb7BpEItFuWBfp4LAgEQgDtcn9Kz/OA9A6mXvrH2kMyCHF7h4xxWVdb3n1jLTS7Ffb8bmNKEsnWQ+hFATfxxuWdF6w3DOlaIW/hu4A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-27T14:26:04Z"
    mac: ENC[AES256_GCM,data:VZljAZ8m9dKhx5utYDM1Qu7zVLev0Gy4nmiPLtF+WnzqNgtWbePnDdjr5t9E6eZTijpUv7V2eRq3XM1v9SaUZ54zHgqnV3cTIcGo4foE3pzuyM0HlgSPOmYAM3oXamW2mn97xpKKnQRWnaahcDnSMG78+G2eAgUXgrDhK2OcAuc=,iv:CsSG9LbXHvTJ7c/GADEiwrbG22D7MrSqAFxGN0auTnc=,tag:nBl4Kcrq+OU/a6sUqOa+yQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
