uptimerobot-operator:
    uptimeRobotApiKey: ENC[AES256_GCM,data:a0GLwVvnddvCLfUJXNjAno+SOUthEG3LpTrgjYzV32Mm,iv:YpY/ezxcYv8VJNrFCTs34ByokSTPsdCoWi3CPQTPdIM=,tag:PjDpAjYUzy2ZN2sd85oLbg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-12-02T09:21:27Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgFR0FX0Y3pjL8aM9obusZHVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbNu6lD/oAypDUNlbAgEQgDvgtVYJZH3Nq9ufOEoBtIOXuoOau0Uj8iVKswmrsfT+RqdQyL4rms2Z4jO60WQw5Bo1MEfTHxb1vL/Ynw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-02T09:21:28Z"
    mac: ENC[AES256_GCM,data:tX+TYq0BoQ0EC8zCdBP8owa46qlJ2bp9KxZwhWOZ4PLifyn6k5etFTCMy1MI2JY0NAFPS5QkE4ifSKznrM/KGrFR8JPvkkC9UmuPJwanx0V7MNLnASXIraisZZYI0Gu4RVJTDpWavZiRqMIWjbxMQ1jea4bpSycNkHlh7HhUk0A=,iv:MiS7oOgoVDgNDab4wQBn2aeXkFXdaQahQMmy/Iyr6lg=,tag:SbOIC7uLOg/SuIV4HpXH1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
