mercure:
  image:
    repository: ghcr.io/dunglas/mercure-saas/mercure-saas
    tag: v0.20.1
  replicaCount: 2
  dev: true
  extraEnvs:
    - name: USE_FORWARDED_HEADERS
      value: "1"
  globalOptions: |
    admin :2019
    servers {
      metrics
    }
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 60s
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 150m
      memory: 128Mi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "24h"
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"

security-template-helm:
  networkPolicies:
    - name: mercure-network-policy
      enabled: false
      egress:
        rules:
          # -- Access to ingress from outside the cluster
          - ports:
              # -- https port
              - port: 443
                protocol: TCP
              # -- MSK Kafka port
              - port: 9096
                protocol: TCP
              # -- Postgresql port
              - port: 5432
                protocol: TCP
            to:
              - ipBlock:
                  cidr: 0.0.0.0/0
          # -- Access to all pod in the same namespace
          - to:
              - podSelector: {}
          # -- Access to all pod
          - to:
              - namespaceSelector: {}
      ingress:
        rules:
          # -- Allow all pod in the same namespace
          - from:
              - podSelector: {}
          # -- Allow all pod to port 9666 (keda operator), 443 (https) and 8080 (metrics)
          - from:
              - namespaceSelector: {}
            ports:
              # -- https port
              - port: 443
                protocol: TCP
              # -- keda operator port
              - port: 9666
                protocol: TCP
              # -- metrics port
              - port: 8080
                protocol: TCP
              # -- Kafka port
              - port: 9096
                protocol: TCP
          # -- Allow the metrics secure port from outside the cluster
          - from:
              - ipBlock:
                  cidr: 0.0.0.0/0
            ports:
              # -- metrics port (secure port)
              - port: 6443
                protocol: TCP
