chronosAppSetPreprod:
  enabled: true

argocd-template-helm:
  default:
    spec:
      project: chronos
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

  argoApps:
    base-tiers-api-preprod:
        enabled: true
        finalizer: true
        appsNameOverride: base-tiers-api-preprod
        spec:
          project: chronos
          source:
            chart: base-tiers-api-helm
            repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
            targetRevision: ">=1.0.0-rc < 1.0.0-rc.x"
            helm:
              ignoreMissingValueFiles: true
              valueFiles:
                - values.yaml
                - values-cronjob.yaml
                - environments/preprod/values.yaml
                - secrets://environments/preprod/secrets.yaml
          destination:
            namespace: base-tiers-api
          syncPolicy:
            automatedEnableDefaultConfig: true

    chronos-staging:
      appsNameOverride: chronos-staging
      enabled: true
      finalizer: true
      spec:
        source:
          repoURL: https://github.com/ManakinCubber/chronos-api
          targetRevision: master
          path: docker/helm
          helm:
            releaseName: chronos-staging
            parameters:
            - name: environmentName
              value: staging
            - name: serviceAccountName
              value: 'arn:aws:iam::990075099095:role/preprod_chronos_role'
            ignoreMissingValueFiles: true
            valueFiles:
            - values.yaml
            - values-api.yaml
            - common-values-cronjobs.yaml
            - common-values-rabbitmq.yaml
            - common-values-workers.yaml
            - Product/Accounting/Expert/values-cronjobs.yaml
            - Product/Accounting/Expert/values-rabbitmq.yaml
            - Product/Accounting/Expert/values-workers.yaml
            - Product/Accounting/GI/values-cronjobs.yaml
            - Product/Accounting/GI/values-rabbitmq.yaml
            - Product/Accounting/GI/values-workers.yaml
            - Product/Accounts/values-cronjobs.yaml
            - Product/Accounts/values-rabbitmq.yaml
            - Product/Accounts/values-workers.yaml
            - Product/Billing/values-cronjobs.yaml
            - Product/Billing/values-rabbitmq.yaml
            - Product/Billing/values-workers.yaml
            - Product/BusinessAccount/values-cronjobs.yaml
            - Product/BusinessAccount/values-rabbitmq.yaml
            - Product/BusinessAccount/values-workers.yaml
            - Product/Data/values-cronjobs.yaml
            - Product/Data/values-rabbitmq.yaml
            - Product/Data/values-workers.yaml
            - Product/Invoice/values-cronjobs.yaml
            - Product/Invoice/values-rabbitmq.yaml
            - Product/Invoice/values-workers.yaml
            - Product/Legal/values-cronjobs.yaml
            - Product/Legal/values-rabbitmq.yaml
            - Product/Legal/values-workers.yaml
            - Product/Protect/values-cronjobs.yaml
            - Product/Protect/values-rabbitmq.yaml
            - Product/Protect/values-workers.yaml
            - Product/Desk/values-cronjobs.yaml
            - Product/Desk/values-rabbitmq.yaml
            - Product/Desk/values-workers.yaml
            - environnements/common/common_color_config.yaml
            - secrets://environnements/common/common_color_secrets.yaml
            - environnements/common/common_preprod_config.yaml
            - secrets://environnements/common/common_preprod_secrets.yaml
            - secrets://environnements/staging/secrets.yaml
            - environnements/staging/config.yaml
        ignoreDifferences:
        - jqPathExpressions:
          - .data
          kind: ConfigMap
          name: chronos-staging-database-config
        - jqPathExpressions:
          - .data
          kind: ConfigMap
          name: audit-database-config
        - jqPathExpressions:
          - .data
          kind: ConfigMap
          name: licence-database-config
        - jqPathExpressions:
          - .spec.replicas
          kind: Deployment
          name: newrelic-main
          group: apps
        destination:
          namespace: chronos-staging

    chronos-testing:
      appsNameOverride: chronos-testing
      enabled: true
      finalizer: true
      spec:
        source:
          repoURL: https://github.com/ManakinCubber/chronos-api
          targetRevision: master
          path: docker/helm
          helm:
            releaseName: chronos-testing
            parameters:
            - name: environmentName
              value: testing
            - name: serviceAccountName
              value: 'arn:aws:iam::990075099095:role/preprod_chronos_role'
            ignoreMissingValueFiles: true
            valueFiles:
            - values.yaml
            - values-api.yaml
            - common-values-cronjobs.yaml
            - common-values-rabbitmq.yaml
            - common-values-workers.yaml
            - Product/Accounting/Expert/values-cronjobs.yaml
            - Product/Accounting/Expert/values-rabbitmq.yaml
            - Product/Accounting/Expert/values-workers.yaml
            - Product/Accounting/GI/values-cronjobs.yaml
            - Product/Accounting/GI/values-rabbitmq.yaml
            - Product/Accounting/GI/values-workers.yaml
            - Product/Accounts/values-cronjobs.yaml
            - Product/Accounts/values-rabbitmq.yaml
            - Product/Accounts/values-workers.yaml
            - Product/Billing/values-cronjobs.yaml
            - Product/Billing/values-rabbitmq.yaml
            - Product/Billing/values-workers.yaml
            - Product/BusinessAccount/values-cronjobs.yaml
            - Product/BusinessAccount/values-rabbitmq.yaml
            - Product/BusinessAccount/values-workers.yaml
            - Product/Data/values-cronjobs.yaml
            - Product/Data/values-rabbitmq.yaml
            - Product/Data/values-workers.yaml
            - Product/Invoice/values-cronjobs.yaml
            - Product/Invoice/values-rabbitmq.yaml
            - Product/Invoice/values-workers.yaml
            - Product/Legal/values-cronjobs.yaml
            - Product/Legal/values-rabbitmq.yaml
            - Product/Legal/values-workers.yaml
            - Product/Protect/values-cronjobs.yaml
            - Product/Protect/values-rabbitmq.yaml
            - Product/Protect/values-workers.yaml
            - Product/Desk/values-cronjobs.yaml
            - Product/Desk/values-rabbitmq.yaml
            - Product/Desk/values-workers.yaml
            - environnements/common/common_color_config.yaml
            - secrets://environnements/common/common_color_secrets.yaml
            - environnements/common/common_preprod_config.yaml
            - secrets://environnements/common/common_preprod_secrets.yaml
            - secrets://environnements/testing/secrets.yaml
            - environnements/testing/config.yaml
        ignoreDifferences:
        - jqPathExpressions:
          - .data
          kind: ConfigMap
          name: chronos-testing-database-config
        - jqPathExpressions:
          - .data
          kind: ConfigMap
          name: audit-database-config
        - jqPathExpressions:
          - .data
          kind: ConfigMap
          name: licence-database-config
        - jqPathExpressions:
          - .spec.replicas
          kind: Deployment
          name: newrelic-main
          group: apps
        destination:
          namespace: chronos-testing

    subscription-manager-development:
      enabled: true
      finalizer: true
      appsNameOverride: subscription-manager-development
      spec:
        source:
          chart: subscription-manager-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0-rc < 1.0.0-rc.x"
          helm:
            valueFiles:
              - values.yaml
              - values-cronjobs.yaml
              - secrets://environments/development/secrets.yaml
              - environments/development/values.yaml
            parameters:
              - name: environmentName
                value: development
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: subscription-manager-development
        ignoreDifferences:
        - jqPathExpressions:
          - .data
          kind: ConfigMap
          name: database-config
        - jqPathExpressions:
          - .spec.replicas
          kind: Deployment
          name: newrelic-main
          group: apps


    subscription-manager-chronos-development:
      enabled: true
      finalizer: true
      appsNameOverride: subscription-manager-chronos-development
      spec:
        source:
          chart: subscription-manager-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0-rc < 1.0.0-rc.x"
          helm:
            valueFiles:
              - values.yaml
              - values-cronjobs.yaml
              - secrets://environments/chronos-development/secrets.yaml
              - environments/chronos-development/values.yaml
            parameters:
              - name: environmentName
                value: chronos-development
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: subscription-manager-chronos-development
        ignoreDifferences:
          - jqPathExpressions:
              - .data
            kind: ConfigMap
            name: database-config
          - jqPathExpressions:
              - .spec.replicas
            kind: Deployment
            name: newrelic-main
            group: apps

    gem-development:
      enabled: true
      finalizer: true
      appsNameOverride: gem-development
      spec:
        source:
          chart: gem-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0-rc < 1.0.0-rc.x"
          helm:
            valueFiles:
              - values.yaml
              - secrets://environments/development/secrets.yaml
              - environments/development/values.yaml
            parameters:
              - name: environmentName
                value: development
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: gem-development
        ignoreDifferences:
          - jqPathExpressions:
              - .data
            kind: ConfigMap
            name: database-config

    hermes-development:
      enabled: true
      finalizer: true
      appsNameOverride: hermes-development
      spec:
        source:
          chart: hermes-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0-rc < 1.0.0-rc.x"
          helm:
            valueFiles:
              - values.yaml
              - secrets://environments/development/secrets.yaml
              - environments/development/values.yaml
            parameters:
              - name: environmentName
                value: development
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: hermes-development

    jirhub:
      enabled: true
      finalizer: true
      appsNameOverride: jirhub
      spec:
        source:
          chart: jirhub-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0"
          helm:
            valueFiles:
              - values.yaml
              - secrets://secrets.yaml
        destination:
          namespace: jirhub
        syncPolicy:
          automatedEnableDefaultConfig: true

    authorization-server:
      appsNameOverride: authorization-server
      enabled: true
      finalizer: true
      spec:
        source:
          chart: authorization-server-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0"
          helm:
            releaseName: authorization-server
            ignoreMissingValueFiles: true
            valueFiles:
              - values.yaml
              - values-preprod.yaml
              - secrets://secrets-preprod.yaml
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: authorization-server
