argocd-template-helm:
  default:
    spec:
      project: hub
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

  argoApps:
    tiime-hub-preprod:
      enabled: true
      finalizer: true
      appsNameOverride: tiime-hub-preprod
      spec:
        source:
          repoURL: 'https://github.com/ManakinCubber/tiime-hub.git'
          path: kubernetes/tiime-hub
          targetRevision: preprod
          helm:
            valueFiles:
              - secrets://environments/preprod/secrets.yaml
            parameters:
              - name: environmentName
                value: preprod
              - name: serviceAccountName
                value: 'arn:aws:iam::990075099095:role/preprod_issuer_tiime_hub_role'
        destination:
          namespace: tiime-hub-preprod

    hub-preprod:
      enabled: true
      finalizer: true
      appsNameOverride: hub-preprod
      spec:
        source:
          chart: hub-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0-rc < 1.0.0-rc.x"
          helm:
            valueFiles:
              - values.yaml
              - environments/preprod/config.yaml
              - secrets://environments/preprod/secrets.yaml
              - environments/preprod/values.yaml
            parameters:
              - name: environmentName
                value: preprod
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: hub-preprod

    hub-numbr-preprod:
      enabled: true
      finalizer: true
      appsNameOverride: hub-numbr-preprod
      spec:
        source:
          chart: hub-helm
          repoURL: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
          targetRevision: ">=1.0.0-rc < 1.0.0-rc.x"
          helm:
            valueFiles:
              - values.yaml
              - environments/numbr-preprod/config.yaml
              - secrets://environments/numbr-preprod/secrets.yaml
              - environments/numbr-preprod/values.yaml
            parameters:
              - name: environmentName
                value: preprod
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: hub-numbr-preprod
