argocd-template-helm:
  default:
    spec:
      project: web
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

  argoApps:
    web:
      appsNameOverride: web
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-ops"
          path: "./charts/web-reverse-proxy"
          targetRevision: "main"
          helm:
            valueFiles:
              - values.yaml
            releaseName: web
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web
    business-onboarding:
      appsNameOverride: business-onboarding
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-business-onboarding"
          path: "./kubernetes"
          targetRevision: "develop"
          helm:
            valueFiles:
              - values.yaml
            releaseName: business-onboarding
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web

    care:
      appsNameOverride: care
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-care"
          path: "./kubernetes"
          targetRevision: "develop"
          helm:
            valueFiles:
              - values.yaml
            releaseName: care
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web

    expert:
      appsNameOverride: expert
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-expert-web.git"
          path: "./kubernetes"
          targetRevision: "release/next"
          helm:
            valueFiles:
              - values.yaml
            releaseName: expert
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web

    apps:
      appsNameOverride: apps
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/chronos-web.git"
          path: "./kubernetes"
          targetRevision: "develop"
          helm:
            valueFiles:
              - values.yaml
            releaseName: apps
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web

    legal:
      appsNameOverride: legal
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-legal-web.git"
          path: "./kubernetes"
          targetRevision: "develop"
          helm:
            valueFiles:
              - values.yaml
            releaseName: legal
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web

    data:
      appsNameOverride: data
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-data-web.git"
          path: "./kubernetes"
          targetRevision: "master"
          helm:
            valueFiles:
              - values.yaml
            releaseName: data
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web

    front-plugin:
      appsNameOverride: front-plugin
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-front-plugin.git"
          path: "./kubernetes"
          targetRevision: "master"
          helm:
            valueFiles:
              - values.yaml
            releaseName: front-plugin
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web

    sign:
      appsNameOverride: sign
      enabled: true
      finalizer: true
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      spec:
        project: web
        source:
          repoURL: "https://github.com/ManakinCubber/tiime-sign-v2"
          path: "./kubernetes"
          targetRevision: "master"
          helm:
            valueFiles:
              - values.yaml
            releaseName: sign
        syncPolicy:
          automatedEnableDefaultConfig: true
        destination:
          namespace: web
