prometheus-elasticsearch-exporter:
    es:
        uri: ENC[AES256_GCM,data:620rhBu4NicCsuITKrKARhAk1IJkuobAIkrrpWKGfe/cRbE06creoJnSjx3nyWrNdLECw4XVZvRRT1vvQGvwQdiz0+vGlBGwn8cbREnm+2JEQWnNTxRg/wBNMRbn,iv:oSdPYIWxGIXvzS6xgE+C7PbAWZf9yeF0Xj8E0B85cxY=,tag:xgaGYIbC4xh8ky2yhTm45w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2024-12-02T09:13:14Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgFxF/Jb5DDx+2A80ylbcLmgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnh1I7BZ5D0z9kJ/fAgEQgDsYSN/FftJIGtOykyM1JSvz8mditMeR5UByi0WvIIUrRDlTDhMgN2tmlx5TU8JUcOocnjNR1j4Xo0AcbQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-02T09:13:14Z"
    mac: ENC[AES256_GCM,data:T+rsdBTpbFFpl9OTPundfblTmvx0yhwSz0UA/jfSNU8GR4I+cSDu1Hi1IvtFTttM/1LP5z9FVb6Aj0Kypey7d2LPvhTI38+ybl6xe55m80fN02ge/wZXVaRzsy3PgwpHySKVXBIVrhX8vJRcWPljJJB2An4ObErjCEL2la4osgQ=,iv:W69aeMrPhW9VpyiZiqotvww8Vvjy8WVUr+fH3eFHnuw=,tag:dhvm3SbYKC1/KbJ9hmSClA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
