redirects:
  pulse.tiime.fr: expert.tiime.fr
  aide.tiime.fr: support.tiime.fr
  signup.tiime.fr: www.tiime.fr/onboarding
  accounts.tiime.fr: apps.tiime.fr/invitation-callback?target_app=accounts
  receipt.tiime.fr: apps.tiime.fr/invitation-callback?target_app=receipt
  invoice.tiime.fr: apps.tiime.fr/invitation-callback?target_app=invoice
  pepit.co: numbr.co
  www.pepit.co: numbr.co
  www2.pepit.co: numbr.co
  ftp.pepit.co: numbr.co
  app.pepit.co: numbr.co
  api.pepit.co: numbr.co
  m.pepit.co: numbr.co
  receipt-dev.tiime.fr: dev.tiime-apps-web.s3-website-eu-west-1.amazonaws.com
  invoice-dev.tiime.fr: dev.tiime-apps-web.s3-website-eu-west-1.amazonaws.com
  receipt-preprod.tiime.fr: staging.tiime-apps-web.s3-website-eu-west-1.amazonaws.com
  invoice-preprod.tiime.fr: staging.tiime-apps-web.s3-website-eu-west-1.amazonaws.com
  www.cubber.com: assets.tiime.fr/mandrill
  www.incityz.com: numbr.co
  incityz.com: numbr.co
  ola-compta.com: numbr.co
  www.ola-compta.com: numbr.co
  www.confluence-expert-comptable.com: numbr.co
  confluence-expert-comptable.com: numbr.co
  cosi-expertise.com: numbr.co
  www.cosi-expertise.com: numbr.co
  evocompta.com: numbr.co
  www.evocompta.com: numbr.co
  o-compta.com: numbr.co
  www.o-compta.com: numbr.co
  condillac-expertise.com: numbr.co
  www.condillac-expertise.com: numbr.co
  novaa-expertise.com: numbr.co
  www.novaa-expertise.com: numbr.co
  goneo-expertise.com: numbr.co
  www.goneo-expertise.com: numbr.co
  #sign.tiime.fr: signature-facile.fr # This one is handled by a dedicated template
  gaspard.pro: numbr.co
  www.gaspard.pro: numbr.co
  coifalia.fr: numbr.co
  www.coifalia.fr: numbr.co
  comptify.fr: numbr.co
  www.comptify.fr: numbr.co
  paradisdufree.fr: numbr.co
  www.paradisdufree.fr: numbr.co
  quaji-expertise.com: numbr.co
  www.quaji-expertise.com: numbr.co
  tsociety.org: numbr.co
  www.tsociety.org: numbr.co
  efixconseil.fr: pepit.eu
  www.efixconseil.fr: pepit.eu
  efixconseil.com: pepit.eu
  www.efixconseil.com: pepit.eu
  le-net-expert-comptable.com: pepit.eu
  www.le-net-expert-comptable.com: pepit.eu
  grafana.tiime.tech: tiime.grafana.net
  databricks.tiime.tech: dbc-8d9bee6c-162a.cloud.databricks.com
  databricks.preprod.tiime.tech: dbc-f7cf1747-7e76.cloud.databricks.com
