github_token: ENC[AES256_GCM,data:SsCAY3W2VEtzLYbRuSu8Vdv7SRYFsERnIudSNaB2DjphlDQZWmmebw==,iv:JrzV132kM55Ab3dE6e3fT3OoG+VZ+KCwjpLCSKwQpoE=,tag:Ihod3+eG55arR/nAcrNlWQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:851725266353:alias/ops
          created_at: "2025-05-15T15:01:20Z"
          enc: AQICAHggmwQugfHwCtKocjaNmNKdi663eGJbZfKulG/9YEGGjgG0poNLd+Eo7V6B/R1xBJL8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1rrrPS5bJMEgd4+dAgEQgDt4zF5m2WcKVSet6i4n+d8AgIyH9diJDYaCYddYWnHPdCvwXqtML9ovPGA5hBHmCfGvaVWEnKTVhuDCfQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-15T15:01:21Z"
    mac: ENC[AES256_GCM,data:jIxh9h+gbWd4sQgBh38ch/aW9NstbtUWs8dha1bJeiwIwQK47llQ1+R5UKBwJL4qpmOtdk1YfnW6VOPiAOZm95SjuKJmJB8GiDs1P6pFPIU9a23sQWcV5bxFMwNnClo/QfAudKen788lRlAkg1a8JuGxdm42lmhFzEBwJ1keuEk=,iv:QsheDUKdCWpwwHe2wUSyhCCJGKvNFpS9+79FEhsk6wA=,tag:artAbRX0k4NGiG/8k0E67g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
