backup:
  cronjobs:
  - command:
    - bash
    - /scripts/db_backups.sh
    - chronos-green
    concurrencyPolicy: Forbid
    name: backup-db
    schedule: 0 0 * * 0
    ephemeral: false
    storage: 100Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 200Mi
  roleArn: arn:aws:iam::990075099095:role/preprod_backups_role
