backup:
  cronjobs:
  - command:
    - bash
    - /scripts/db_backups.sh
    - chronos-prod
    concurrencyPolicy: Forbid
    name: backup-chronos-prod
    schedule: 0 1 * * *
    ephemeral: true
    storage: 800Gi
    backoffLimit: 0
    resources:
      requests:
        cpu: 2
        memory: 200Mi
      limits:
        memory: 200Mi
  - command:
    - bin/bash
    - /scripts/1password.sh
    concurrencyPolicy: Forbid
    name: 1password
    schedule: 10 0 * * *
    ephemeral: true
  - command:
    - bin/bash
    - /scripts/hubspot.sh
    - '&&'
    - curl
    - -fss
    - -m
    - "10"
    - --retry
    - "5"
    - -o
    - /dev/null
    - https://hc-ping.com/8f0c8f2a-0ad7-47ec-b292-9f9095bb71fb
    concurrencyPolicy: Forbid
    name: hubspot
    schedule: 45 0 * * *
    ephemeral: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 200Mi
  - command:
    - bin/bash
    - /scripts/sites-daily.sh
    - '&&'
    - curl
    - -fss
    - -m
    - "10"
    - --retry
    - "5"
    - -o
    - /dev/null
    - https://hc-ping.com/c6448552-b4f9-413d-b4d2-9e466cc0c8f8
    concurrencyPolicy: Forbid
    name: sites-daily
    schedule: 30 3 2-31 * *
    ephemeral: true
  - command:
    - bin/bash
    - /scripts/sites-monthly.sh
    - '&&'
    - curl
    - -fss
    - -m
    - "10"
    - --retry
    - "5"
    - -o
    - /dev/null
    - https://hc-ping.com/b7500651-5ab5-4bda-a8eb-9b8779f7bf66
    concurrencyPolicy: Forbid
    name: sites-monthly
    schedule: 30 3 1 * *
    ephemeral: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 200Mi
  - command:
    - python3
    - /scripts/mandrill.py
    - '>'
    - '&&'
    - curl
    - -fss
    - -m
    - "10"
    - --retry
    - "5"
    - -o
    - /dev/null
    - https://hc-ping.com/48c3eaff-649d-4c00-8bd5-9e84d3f35c86
    concurrencyPolicy: Forbid
    name: mandrill
    schedule: 0 2 * * *
    ephemeral: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 200Mi
  roleArn: arn:aws:iam::284983278621:role/tiime-prod_backups_role
