karpenter:
  webhook:
    serviceNamespace: karpenter
  serviceMonitor:
    enabled: true
  settings:
    clusterName: tiime-prod
    interruptionQueue: Karpenter-tiime-prod
  eksControlPlane: true
  featureGates:
    spotToSpotConsolidation: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::284983278621:role/KarpenterControllerRole-tiime-prod
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
  tolerations:
    - key: tiime.tech/karpenter-managed
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: karpenter.sh/registered
            operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

nodePools:
  common:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels: {}
    taints: {}
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.4xlarge
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - m7g.4xlarge
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - r7g.4xlarge
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - r8g.4xlarge
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - c7i.4xlarge
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - m7i.4xlarge
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i-flex.4xlarge
        - m7i-flex.2xlarge
        - m7i-flex.xlarge
        - m7i-flex.large
        - r7i.4xlarge
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64

  common-no-overcommit:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: tiime.tech/qos
      value: guaranteed
    taints:
    - key: tiime.tech/qos
      effect: NoSchedule
      value: guaranteed
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i-flex.2xlarge
        - m7i-flex.xlarge
        - m7i-flex.large
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64

  data-flink:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: dedicated
      value: flink
    taints:
    - key: dedicated
      effect: NoSchedule
      value: flink
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.4xlarge
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - m7g.4xlarge
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - r7g.4xlarge
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - r8g.4xlarge
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - c7i.4xlarge
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - m7i.4xlarge
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i-flex.4xlarge
        - m7i-flex.2xlarge
        - m7i-flex.xlarge
        - m7i-flex.large
        - r7i.4xlarge
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  data-memory:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: dedicated
      value: chronos-importer
    taints:
    - key: dedicated
      effect: NoSchedule
      value: chronos-importer
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - r5.4xlarge
        - r5a.4xlarge
        - r6i.4xlarge
        - r6a.4xlarge
        - r7i.4xlarge
        - r7a.4xlarge
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  data-compute:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: dedicated
      value: ekoo
    taints:
    - key: dedicated
      effect: NoSchedule
      value: ekoo
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7i.16xlarge
        - c7a.16xlarge
        - c6i.16xlarge
        - c6a.16xlarge
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  common-no-consolidate-workday:
    duration: 11h
    nodes: "0"
    nodeClassRef: node-class-private
    labels:
    - name: tiime.tech/consolidate
      value: common-no-consolidate-workday
    taints:
    - key: tiime.tech/consolidate
      effect: NoSchedule
      value: common-no-consolidate-workday
    schedule: 0 9 * * mon-fri
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.4xlarge
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - m7g.4xlarge
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - r7g.4xlarge
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - r8g.4xlarge
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - c7i.4xlarge
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - m7i.4xlarge
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i-flex.4xlarge
        - m7i-flex.2xlarge
        - m7i-flex.xlarge
        - m7i-flex.large
        - r7i.4xlarge
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64

  public:
    nodeClassRef: node-class-public
    disruption:
      consolidateAfter: 15m
    labels:
    - name: tiime.tech/networking
      value: public
    taints:
    - key: tiime.tech/networking
      effect: NoSchedule
      value: public
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.medium
        - m7g.medium
        - m7g.xlarge
        - r7g.medium
        - c8g.medium
        - m8g.medium
        - m8g.xlarge
        - r8g.medium
        - t4g.large
        - t4g.medium
        - t4g.small
        - t3.medium
        - t3.small
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64
