karpenter:
  webhook:
    serviceNamespace: karpenter
  nodeRole:
  serviceMonitor:
    enabled: true
  settings:
    clusterName: preprod
    interruptionQueue: Karpenter-preprod
  eksControlPlane: true
  featureGates:
    spotToSpotConsolidation: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::990075099095:role/KarpenterControllerRole-preprod
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
  postInstallHook:
    image:
      repository: bitnami/kubectl
      digest: sha256:75243f00f9d7313cbf0142258edab749f9b4461f8efbbe970df1193c7aef35a0
  tolerations:
    - key: tiime.tech/karpenter-managed
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: karpenter.sh/registered
            operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

nodePools:
  common:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels: {}
    taints: {}
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.4xlarge
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - c7g.medium
        - m7g.4xlarge
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - m7g.medium
        - r7g.4xlarge
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - r7g.medium
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - c8g.medium
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - m8g.medium
        - r8g.4xlarge
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - r8g.medium
        - c7i.4xlarge
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - c7i.medium
        - m7i.4xlarge
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i.medium
        - r7i.4xlarge
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
        - r7i.medium
        - c7a.4xlarge
        - c7a.2xlarge
        - c7a.xlarge
        - c7a.large
        - c7a.medium
        - m7a.4xlarge
        - m7a.2xlarge
        - m7a.xlarge
        - m7a.large
        - m7a.medium
        - r7a.4xlarge
        - r7a.2xlarge
        - r7a.xlarge
        - r7a.large
        - r7a.medium
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64

  common-no-overcommit:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: tiime.tech/qos
      value: guaranteed
    taints:
    - key: tiime.tech/qos
      effect: NoSchedule
      value: guaranteed
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.4xlarge
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - m7g.4xlarge
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - r7g.4xlarge
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - r8g.4xlarge
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - c7i.4xlarge
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - m7i.4xlarge
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i-flex.4xlarge
        - m7i-flex.2xlarge
        - m7i-flex.xlarge
        - m7i-flex.large
        - r7i.4xlarge
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64

  data-flink:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: dedicated
      value: flink
    taints:
    - key: dedicated
      effect: NoSchedule
      value: flink
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.4xlarge
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - m7g.4xlarge
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - r7g.4xlarge
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - r8g.4xlarge
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - c7i.4xlarge
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - m7i.4xlarge
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i-flex.4xlarge
        - m7i-flex.2xlarge
        - m7i-flex.xlarge
        - m7i-flex.large
        - r7i.4xlarge
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  data-memory:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: dedicated
      value: chronos-importer
    taints:
    - key: dedicated
      effect: NoSchedule
      value: chronos-importer
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - r5.4xlarge
        - r5a.4xlarge
        - r6i.4xlarge
        - r6a.4xlarge
        - r7i.4xlarge
        - r7a.4xlarge
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  data-compute:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: dedicated
      value: ekoo
    taints:
    - key: dedicated
      effect: NoSchedule
      value: ekoo
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7i.16xlarge
        - c7a.16xlarge
        - c6i.16xlarge
        - c6a.16xlarge
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  data-jupyter-hub:
    nodeClassRef: node-class-private
    type: consolidate
    duration: 11h
    nodes: "0"
    schedule: 0 9 * * mon-fri
    labels:
    - name: dedicated
      value: jupyter-hub
    taints:
    - key: dedicated
      effect: NoSchedule
      value: jupyter-hub
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - r6i.4xlarge
        - r6a.4xlarge
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  data-jupyter-hub-gpu:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: dedicated
      value: jupyter-hub-gpu
    taints:
    - key: dedicated
      effect: NoSchedule
      value: jupyter-hub-gpu
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - g5.8xlarge
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64

  common-no-consolidate-workday:
    type: consolidate
    duration: 11h
    nodes: "0"
    nodeClassRef: node-class-private
    labels:
    - name: tiime.tech/consolidate
      value: common-no-consolidate-workday
    schedule: 0 9 * * mon-fri
    taints:
    - key: tiime.tech/consolidate
      effect: NoSchedule
      value: common-no-consolidate-workday
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.4xlarge
        - c7g.2xlarge
        - c7g.xlarge
        - c7g.large
        - m7g.4xlarge
        - m7g.2xlarge
        - m7g.xlarge
        - m7g.large
        - r7g.4xlarge
        - r7g.2xlarge
        - r7g.xlarge
        - r7g.large
        - c8g.4xlarge
        - c8g.2xlarge
        - c8g.xlarge
        - c8g.large
        - m8g.4xlarge
        - m8g.2xlarge
        - m8g.xlarge
        - m8g.large
        - r8g.4xlarge
        - r8g.2xlarge
        - r8g.xlarge
        - r8g.large
        - c7i.4xlarge
        - c7i.2xlarge
        - c7i.xlarge
        - c7i.large
        - m7i.4xlarge
        - m7i.2xlarge
        - m7i.xlarge
        - m7i.large
        - m7i-flex.4xlarge
        - m7i-flex.2xlarge
        - m7i-flex.xlarge
        - m7i-flex.large
        - r7i.4xlarge
        - r7i.2xlarge
        - r7i.xlarge
        - r7i.large
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64

  public:
    nodeClassRef: node-class-public
    disruption:
      consolidateAfter: 15m
    labels:
    - name: tiime.tech/networking
      value: public
    taints:
    - key: tiime.tech/networking
      effect: NoSchedule
      value: public
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - c7g.medium
        - m7g.medium
        - r7g.medium
        - c8g.medium
        - m8g.medium
        - r8g.medium
        - t4g.large
        - t4g.medium
        - t4g.small
        - t3.medium
        - t3.small
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - arm64
        - amd64
  llm:
    nodeClassRef: node-class-private
    disruption:
      consolidateAfter: 15m
    labels:
    - name: tiime.tech/dedicated
      value: llm
    taints:
    - key: tiime.tech/dedicated
      effect: NoSchedule
      value: llm
    requirements:
      - name: node.kubernetes.io/instance-type
        operator: In
        type:
        - g5.2xlarge
        - g5.xlarge
      - name: topology.kubernetes.io/zone
        operator: In
        type:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - name: karpenter.sh/capacity-type
        operator: In
        type:
        - spot
        - on-demand
      - name: kubernetes.io/arch
        operator: In
        type:
        - amd64
