apiVersion: batch/v1
kind: CronJob
metadata:
  name: stop-rds-database
spec:
  schedule: "0 22 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Release.Name }}
          volumes:
            - name: stop-rds-script
              configMap:
                name: stop-rds
                defaultMode: 444
          containers:
            - name: script
              image: amazon/aws-cli:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: stop-rds-script
                  mountPath: /home/aws
              command:
                - /bin/bash
                - -c
                - /home/aws/script.sh
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-rds-database
spec:
  schedule: "0 22 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Release.Name }}
          volumes:
            - name: delete-rds-script
              configMap:
                name: delete-rds
                defaultMode: 444
          containers:
            - name: script
              image: amazon/aws-cli:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: delete-rds-script
                  mountPath: /home/aws
              command:
                - /bin/bash
                - -c
                - /home/aws/script.sh
