apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-links
data:
  assetlinks.conf: |
    server {
        listen 8080;
        server_name receipt.tiime.fr accounts.tiime.fr;

        location = /.well-known/assetlinks.json {
            default_type "application/json";
            return 200 '[{"relation":["delegate_permission/common.handle_all_urls"],"target":{"namespace":"android_app","package_name":"fr.tiime.receipt","sha256_cert_fingerprints":["EA:20:1A:8F:FD:BB:57:C9:32:E8:EA:8C:83:59:76:C6:FE:4B:04:CD:7C:D6:ED:17:F6:D6:9C:57:66:CC:67:A8"]}}]';
        }

        location = /.well-known/apple-app-site-association {
            default_type "application/json";
            return 200 '[{  "applinks": {"details": [{"appIDs": ["2THRS735Y7.fr.tiime.Receipt"], "components": [{"/": "/redirect/*", "exclude": true, "comment": "Handle internal redirections"}]}]}}]';
        }
    }

    server {
        listen 8080;
        server_name invoice.tiime.fr;

        location = /.well-known/assetlinks.json {
            default_type "application/json";
            return 200 '[{"relation":["delegate_permission/common.handle_all_urls"],"target":{"namespace":"android_app","package_name":"fr.tiime.invoice","sha256_cert_fingerprints":["EA:20:1A:8F:FD:BB:57:C9:32:E8:EA:8C:83:59:76:C6:FE:4B:04:CD:7C:D6:ED:17:F6:D6:9C:57:66:CC:67:A8"]}}]';
        }

        location = /.well-known/apple-app-site-association {
            default_type "application/json";
            return 200 '[{  "applinks": {"details": [{"appIDs": ["2THRS735Y7.fr.tiime.Invoice"],"components": [{"/": "/redirect/*", "exclude": true, "comment": "Handle internal redirections"}]}]}}]';
        }
    }

    server {
        listen 8080;
        server_name receipt-dev.tiime.fr;

        location = /.well-known/apple-app-site-association {
            default_type "application/json";
            return 200 '[{"applinks":{"details":[{"appIDs": ["2THRS735Y7.fr.tiime.ReceiptDevelopment"], "components": [{"/": "/redirect/*", "exclude": true, "comment": "Handle internal redirections"}]}]}}]';
        }
    }

    server {
        listen 8080;
        server_name receipt-preprod.tiime.fr;

        location = /.well-known/apple-app-site-association {
            default_type "application/json";
            return 200 '[{"applinks": {"details": [{"appIDs": ["2THRS735Y7.fr.tiime.ReceiptPreprod"], "components": [{"/": "/redirect/*", "exclude": true, "comment": "Handle internal redirections"}]}]}}]';
        }
    }

    server {
        listen 8080;
        server_name invoice-dev.tiime.fr;

        location = /.well-known/apple-app-site-association {
            default_type "application/json";
            return 200 '[{"applinks": {"details": [{"appIDs": ["2THRS735Y7.fr.tiime.InvoiceDev"], "components": [{"/": "/redirect/*", "exclude": true, "comment": "Handle internal redirections"}]}]}}]';
        }
    }
    
    server {
        listen 8080;
        server_name invoice-preprod.tiime.fr;

        location = /.well-known/apple-app-site-association {
            default_type "application/json";
            return 200 '[{"applinks": {"details": [{"appIDs": ["2THRS735Y7.fr.tiime.InvoicePreprod"], "components": [{"/": "/redirect/*", "exclude": true, "comment": "Handle internal redirections"}]}]}}]';
        }
    }
