kubernetesRolesBinding:
  - name: "chronos"
    roles:
      - namespace: "chronos-production"
      - namespace: "chronos-school"
      - namespace: "subscription-manager-production"
      - namespace: "gem-production"
  - name: "data"
    roles:
      - namespace: "ds-prod"
  - name: "data-platform"
    roles:
      - namespace: "flink"
  - name: "tiime-hub"
    roles:
      - namespace: "hub-prod"
  - name: "hub-numbr-prod"
    roles:
      - namespace: "hub-numbr-prod"
  - name: "hub"
    roles:
      - namespace: "hub-school"
      - namespace: "hub-prod"
      - namespace: "tiime-hub-production"
      - namespace: "base-tiers-api"
      - namespace: "hub-numbr-prod"
  - name: "llm"
    roles:
      - namespace: "llm-production"
  - name: "hermes"
    roles:
      - namespace: "hermes-production"
