kubernetesRolesBinding:
  - name: "data"
    roles:
      - namespace: "data-analytics-dev"
      - namespace: "ds-dev-dagobah"
      - namespace: "ds-dev-endor"
      - namespace: "ds-dev-naboo"
      - namespace: "ds-dev-tatooine"
      - namespace: "ds-staging"
  - name: "data-platform"
    roles:
      - namespace: "flink"
  - name: "chronos"
    roles:
      - namespace: "chronos-review-green"
      - namespace: "chronos-review-orange"
      - namespace: "chronos-review-red"
      - namespace: "chronos-review-pink"
      - namespace: "chronos-review-blue"
      - namespace: "chronos-review-yellow"
      - namespace: "chronos-review-purple"
      - namespace: "chronos-review-grey"
      - namespace: "chronos-review-indigo"
      - namespace: "chronos-review-onyx"
      - namespace: "chronos-review-cinereous"
      - namespace: "chronos-review-lavender"
      - namespace: "chronos-review-amaranth"
      - namespace: "chronos-review-cerfrance"
      - namespace: "chronos-review-black"
      - namespace: "chronos-review-brown"
      - namespace: "chronos-review-white"
      - namespace: "chronos-review-teal"
      - namespace: "chronos-review-leafy"
      - namespace: "chronos-review-pistachio"
      - namespace: "chronos-debug"
      - namespace: "chronos-development"
      - namespace: "chronos-staging"
      - namespace: "chronos-testing"
      - namespace: "subscription-manager-development"
      - namespace: "subscription-manager-chronos-development"
      - namespace: "gem-development"
      - namespace: "hermes-development"
      - namespace: "mercure"
  - name: "tiime-hub"
    roles:
      - namespace: "tiime-hub-black"
      - namespace: "tiime-hub-blue"
      - namespace: "tiime-hub-orange"
      - namespace: "tiime-hub-preprod"
      - namespace: "tiime-hub-red"
      - namespace: "tiime-hub-yellow"
      - namespace: "hub-preprod"
      - namespace: "base-tiers-api"
  - name: "hub-numbr-preprod"
    roles:
      - namespace: "hub-numbr-preprod"
  - name: "hub"
    roles:
      - namespace: "hub-preprod"
      - namespace: "base-tiers-api"
  - name: "llm"
    roles:
      - namespace: "llm-preprod"
  - name: "miscellaneous"
    roles:
      - namespace: "tiime-addok"
