apiVersion: v1
kind: Secret
metadata:
  name: {{include "database.secretName" .}}
  labels: {{- include "database.labels" $ | nindent 4}}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  password: {{.Values.database.password}}
