cert-manager-issuer:
  email: devops_alerts@tiime.fr
  issuers:
  - kind: ClusterIssuer
    method:
    - http01:
        ingress:
          class: nginx
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
  - kind: ClusterIssuer
    method:
    - dns01:
        route53:
          hostedZoneID: Z05238141PDU83FQ17EX0
          region: eu-west-1
          role: arn:aws:iam::851725266353:role/shared_dns_role
    name: letsencrypt-prod-dns01
    privateKeySecretRef:
      name: letsencrypt-prod-dns01
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
        - tiime.tech
