apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: job-failed-by-team
spec:
  groups:
    - name: jobs_alerting
      rules:
        - alert: KubeJobFailed
          annotations:
            chronos_description: >-
              Il a été impossible d'effectuer {{ "{{ $labels.namespace }}/{{ $labels.job_name }}" }}

              <https://tiime.grafana.net/explore?schemaVersion=1&panes=%7B%22oe4%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22{{ "{{ $labels.namespace }}" }}%5C%22,%20cluster%3D%5C%22{{ "{{ $labels.cluster }}" }}%5C%22%7D%20%7C%3D%20%60{{ "{{ $labels.job_name }}" }}%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22direction%22:%22backward%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1
              | Voir les logs du job>
            description: >-
              Job {{ "{{ $labels.namespace }}/{{ $labels.job_name }}" }} failed to
              complete. Removing failed job after investigation should clear
              this alert.
            runbook_url: >-
              https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubejobfailed
            summary: Job failed to complete.
          expr: >-
            kube_job_failed{condition="true",job="integrations/kubernetes/kube-state-metrics",namespace=~".*", cluster=~{{ (index $.Values "k8s-monitoring").cluster.name | quote }} }
            * on (pod, job_name, namespace) group_left (label_tiime_tech_team)
            kube_job_labels{job="integrations/kubernetes/kube-state-metrics",namespace=~".*"} > 0
          for: 1m
          labels:
            severity: warning
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pods-crash
spec:
  groups:
    - name: pods_failure
      rules:
        - alert: KubePodOOM
          annotations:
            description: >-
              Pod {{ "{{ $labels.namespace }}/{{ $labels.pod }}" }} failed due to Out Of
              Memory issue. Increase its resource limitations or watch its
              memory usage to see if something went wrong.
            summary: Out Of Memory event detected.
          expr: >-
            kube_pod_container_status_last_terminated_reason{reason="OOMKilled",
            job="integrations/kubernetes/kube-state-metrics", cluster=~{{ (index $.Values "k8s-monitoring").cluster.name | quote }}}
            and on(namespace, pod, container) (increase(kube_pod_container_status_restarts_total{cluster=~{{ (index $.Values "k8s-monitoring").cluster.name | quote }}}[30m]) > 0)
          labels:
            severity: warning
