aws:
  prod:
    registry: 284983278621.dkr.ecr.eu-central-1.amazonaws.com
  shared:
    registry: 851725266353.dkr.ecr.eu-central-1.amazonaws.com
argo-cd:
  global:
    networkPolicy:
      create: true
    tolerations:
      - key: "tiime.tech/karpenter-managed"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: karpenter.sh/registered
                  operator: DoesNotExist
  configs:
    params: 
      controller.resource.health.persist: true
    cm:
      statusbadge.enabled: "true"
      statusbadge.url: "https://argo.tiime.tech/"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $clientID
              clientSecret: $clientSecret
              orgs:
              - name: ManakinCubber
      helm.valuesFileSchemes:
        secrets+gpg-import, secrets+gpg-import-kubernetes, secrets+age-import,
        secrets+age-import-kubernetes, secrets, https
      url: https://argo.tiime.tech
    secret:
      argocdServerAdminPassword: $2a$10$h21ydxr6EIHb3IYUTBP./O9f4HsZZNY5PUx.VkIdTfz6Tsj1dRP1a
  applicationSet:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  controller:
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 2
        memory: 2Gi
  dex:
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
  notifications:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redis:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  repoServer:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::284983278621:role/tiime-prod_argocd_role
  server:
    resources:
      limits:
        memory: 356Mi
      requests:
        cpu: 50m
        memory: 64Mi
    certificate:
      additionalHosts: []
      domain: argo.tiime.tech
      enabled: true
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-prod
      secretName: argocd-server-tls
    ingress:
      enabled: true
      # Implemented in argocd v6. may be usefull to configure behind the AWS WAF
      # controller: aws
      # annotations:
      #   alb.ingress.kubernetes.io/backend-protocol: HTTPS
      #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      # aws:
      #   backendProtocolVersion: HTTP2
      #   serviceType: NodePort
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      hostname: argo.tiime.tech
      tls: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::284983278621:role/tiime-prod_argocd_role
      automountServiceAccountToken: true
      create: true
      name: argocd-server
