argo-cd:
  configs:
    rbac:
      policy.csv: |
        p, role:chronos, applications, get, chronos/*, allow
        p, role:chronos, applications, update, chronos/*, allow
        p, role:chronos, applications, update/*, chronos/*, allow
        p, role:chronos, applications, sync, chronos/*, allow
        p, role:chronos, applications, delete/*/Job/*, chronos/*, allow
        p, role:chronos, applications, delete/*/Queue/*, chronos/*, allow
        p, role:chronos, applications, delete/*/Binding/*, chronos/*, allow
        p, role:chronos, applications, override, chronos/*, allow
        p, role:chronos, applications, action/*, chronos/*, allow
        p, role:chronos, repositories, get, https://github.com/ManakinCubber/chronos-api, allow
        p, role:chronos, projects, get, chronos, allow
        p, role:chronos, exec, create, chronos/*, allow
        p, role:chronos, logs, get, chronos/*, allow

        p, role:data, applications, get, data/*, allow
        p, role:data, applications, update, data/*, allow
        p, role:data, applications, update/*, data/*, allow
        p, role:data, applications, sync, data/*, allow
        p, role:data, applications, override, data/*, allow
        p, role:data, applications, action/*, data/*, allow
        p, role:data, repositories, get, https://github.com/ManakinCubber/data-science, allow
        p, role:data, projects, get, data, allow
        p, role:data, exec, create, data/*, allow
        p, role:data, logs, get, data/*, allow

        p, role:data-science, applications, get, data-science/*, allow
        p, role:data-science, applications, update, data-science/*, allow
        p, role:data-science, applications, update/*, data-science/*, allow
        p, role:data-science, applications, sync, data-science/*, allow
        p, role:data-science, applications, delete, data-science/*, allow
        p, role:data-science, applications, override, data-science/*, allow
        p, role:data-science, applications, action/*, data-science/*, allow
        p, role:data-science, repositories, get, https://github.com/ManakinCubber/data-science, allow
        p, role:data-science, projects, get, data-science, allow
        p, role:data-science, exec, create, data-science/*, allow
        p, role:data-science, logs, get, data-science/*, allow

        p, role:data-engineering, applications, get, data-engineering/*, allow
        p, role:data-engineering, applications, update, data-engineering/*, allow
        p, role:data-engineering, applications, update/*, data-engineering/*, allow
        p, role:data-engineering, applications, sync, data-engineering/*, allow
        p, role:data-engineering, applications, delete, data-engineering/*, allow
        p, role:data-engineering, applications, delete/*, data-engineering/*, allow
        p, role:data-engineering, applications, override, data-engineering/*, allow
        p, role:data-engineering, applications, action/*, data-engineering/*, allow
        p, role:data-engineering, repositories, get, https://github.com/ManakinCubber/data-science, allow
        p, role:data-engineering, projects, get, data-engineering, allow
        p, role:data-engineering, exec, create, data-engineering/*, allow
        p, role:data-engineering, logs, get, data-engineering/*, allow

        p, role:data-analytics, applications, get, data-analytics/*, allow
        p, role:data-analytics, applications, update, data-analytics/*, allow
        p, role:data-analytics, applications, update/*, data-analytics/*, allow
        p, role:data-analytics, applications, sync, data-analytics/*, allow
        p, role:data-analytics, applications, delete, data-analytics/*, allow
        p, role:data-analytics, applications, delete/*, data-analytics/*, allow
        p, role:data-analytics, applications, override, data-analytics/*, allow
        p, role:data-analytics, applications, action/*, data-analytics/*, allow
        p, role:data-analytics, projects, get, data-analytics, allow
        p, role:data-analytics, exec, create, data-analytics/*, allow
        p, role:data-analytics, logs, get, data-analytics/*, allow

        p, role:data-science-ro, applications, get, data-science/*, allow
        p, role:data-science-ro, projects, get, data-science, allow

        p, role:data-engineering-ro, applications, get, data-engineering/*, allow
        p, role:data-engineering-ro, projects, get, data-engineering, allow

        p, role:data-analytics-ro, applications, get, data-analytics/*, allow
        p, role:data-analytics-ro, projects, get, data-analytics, allow

        p, role:hub, applications, get, hub/*, allow
        p, role:hub, applications, update, hub/*, allow
        p, role:hub, applications, update/*, hub/*, allow
        p, role:hub, applications, sync, hub/*, allow
        p, role:hub, applications, override, hub/*, allow
        p, role:hub, applications, action/*, hub/*, allow
        p, role:hub, projects, get, data, allow
        p, role:hub, exec, create, hub/*, allow
        p, role:hub, logs, get, hub/*, allow

        p, role:llm, applications, get, llm/*, allow
        p, role:llm, applications, update, llm/*, allow
        p, role:llm, applications, update/*, llm/*, allow
        p, role:llm, applications, sync, llm/*, allow
        p, role:llm, applications, delete/*/Job/*, llm/*, allow
        p, role:llm, applications, override, llm/*, allow
        p, role:llm, applications, action/*, llm/*, allow
        p, role:llm, repositories, get, https://github.com/ManakinCubber/llm, allow
        p, role:llm, projects, get, llm, allow
        p, role:llm, exec, create, llm/*, allow
        p, role:llm, logs, get, llm/*, allow

        p, role:front, applications, get, chronos/*, allow
        p, role:front, applications, get, web/*, allow
        p, role:front, repositories, get, https://github.com/ManakinCubber/chronos-api, allow
        p, role:front, projects, get, chronos, allow
        p, role:front, projects, get, web, allow
        p, role:front, logs, get, chronos/*, allow
        p, role:front, logs, get, web/*, allow

        g, "ManakinCubber:Devops", role:admin
        g, "ManakinCubber:Back", role:chronos
        g, "ManakinCubber:Back", role:front
        g, "ManakinCubber:Data", role:data
        g, "ManakinCubber:Data Science", role:data-science
        g, "ManakinCubber:Data Engineering", role:data-engineering
        g, "ManakinCubber:Data Analytics", role:data-analytics
        g, "ManakinCubber:Analytics", role:data
        g, "ManakinCubber:Hub", role:hub
        g, "ManakinCubber:Web", role:front
        g, "ManakinCubber:Llm", role:llm
        g, "ManakinCubber:ReadOnly", role:readonly

        g, data-science, role:data-science-ro
        g, data-engineering, role:data-engineering-ro
        g, data-engineering, role:data-science-ro
        g, data-analytics, role:data-analytics-ro

      policy.default: ""
