apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: node-class-private
spec:
  # required, resolves a default ami and userdata
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest

  # metadata options Hop limit increase to 2 to access ec2 metadata
  metadataOptions:
    httpPutResponseHopLimit: 2

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        iops: 3000
        encrypted: true
        deleteOnTermination: true
        throughput: 125

  # required, discovers subnets to attach to instances
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName | quote }}
        tiime.tech:network:subnet:type: "private"

  # required, discovers security groups to attach to instances
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName | quote }}

  # required, IAM role to use for the node identity
  role: "KarpenterNodeRole-{{ .Values.karpenter.settings.clusterName }}"
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: node-class-public
spec:
  # required, resolves a default ami and userdata
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest

  # metadata options Hop limit increase to 2 to access ec2 metadata
  metadataOptions:
    httpPutResponseHopLimit: 2

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        iops: 3000
        encrypted: true
        deleteOnTermination: true
        throughput: 125

  # required, discovers subnets to attach to instances
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName | quote }}
        tiime.tech:network:subnet:type: "public"

  # required, discovers security groups to attach to instances
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName | quote }}

  # required, IAM role to use for the node identity
  role: "KarpenterNodeRole-{{ .Values.karpenter.settings.clusterName }}"
