{{- range $name, $nodePool := .Values.nodePools }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $name }}
spec:
  disruption:
    consolidateAfter: {{ ($nodePool.disruption).consolidateAfter | default "30s" }}
    consolidationPolicy: {{ ($nodePool.disruption).consolidationPolicy | default "WhenEmptyOrUnderutilized" }}
    {{-  if or (hasKey $nodePool "schedule") (hasKey $nodePool "duration") }}
    budgets:
      - schedule: {{ $nodePool.schedule | required "The schedule parameter for budget disruption" }}
        duration: {{ $nodePool.duration | required "The duration parameter for budget disruption" }}
        nodes: "{{ $nodePool.nodes }}"
    {{- end }}
  weight: {{ $nodePool.weight | default 1 }}
  template:
  {{- if or (hasKey $nodePool "labels") (hasKey $nodePool "annotations") }}
    metadata:
      {{- if hasKey $nodePool "labels" }}
      labels:
        {{- range $i, $label := $nodePool.labels }}
        {{ $label.name }}: {{ $label.value }}
        {{ end -}}
      {{ end -}}
      {{- if hasKey $nodePool "annotations" }}
      annotations:
        {{- range $i, $annotation := $nodePool.annotations }}
        {{ $annotation.name }}: {{ $annotation.value }}
        {{ end -}}
      {{ end -}}
  {{- end }}
    spec:
      expireAfter: {{ ($nodePool.disruption).expireAfter | default "168h" }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ required "The node class ref of the NodePool is required!" $nodePool.nodeClassRef }}
      {{- if hasKey $nodePool "taints" }}
      taints:
      {{- range $name, $taint := $nodePool.taints }}
      - key: {{ $taint.key }}
        effect: {{ $taint.effect }}
        value: {{ $taint.value | quote }}
      {{- end }}
      {{- end }}
      requirements:
      {{- range $key, $val := $nodePool.requirements }}
        - key: {{ $val.name | quote }}
          operator: {{ $val.operator }}
          values:
          {{- range $val.type }}
          - {{ . | quote }}
          {{- end }}
      {{- end }}
---
{{- end }}
